import Link from 'next/link';
import { notFound } from 'next/navigation';
import ProductGallery from '@/components/ProductGallery';
import ProductVisual from '@/components/ProductVisual';
import ProductPageActions from '@/components/ProductPageActions';
import BookingActions from '@/components/BookingActions';
import ReviewSummaryPanel from '@/components/ReviewSummaryPanel';
import { getProduct, getProducts } from '@/lib/sanity-products';
import { getProductReviewSummary, getPublicReviewsForProduct, getUserReviewSummary, resolveUserIdFromSanityProfile } from '@/lib/review-summaries';
import { calculateRentalPricing } from '@/lib/rental-pricing';
import { CANCELLATION_POLICIES, cancellationDeadlines, policySummary } from '@/lib/cancellation-policy';
import type { CancellationPolicy } from '@/lib/products';
import { BackIcon, CheckIcon, ForwardIcon } from '@/components/Icons';
import styles from './owner-card.module.css';

function firstSentence(text?:string){if(!text)return'';const normalized=text.replace(/\s+/g,' ').trim(),match=normalized.match(/^(.+?[.!?])(?:\s|$)/);return(match?.[1]??normalized).slice(0,190)}
function formatRentalDate(value:string,en:boolean){return new Intl.DateTimeFormat(en?'en-GB':'sv-SE',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`)).replace('.','.')}
function formatResponseTime(minutes:number,en:boolean){if(minutes<=5)return en?'Replies in a few minutes':'Svarar inom några minuter';if(minutes<=15)return en?'Usually replies within 15 minutes':'Svarar oftast inom 15 minuter';if(minutes<=30)return en?'Usually replies within 30 minutes':'Svarar oftast inom 30 minuter';if(minutes<=60)return en?'Usually replies within 1 hour':'Svarar oftast inom 1 timme';const hours=Math.ceil(minutes/60);if(hours<=24)return en?`Usually replies within ${hours} hours`:`Svarar oftast inom ${hours} timmar`;const days=Math.ceil(hours/24);return en?`Usually replies within ${days} ${days===1?'day':'days'}`:`Svarar oftast inom ${days} ${days===1?'dag':'dagar'}`}
type SearchContext={q?:string;category?:string;from?:string;to?:string;place?:string;radius?:string;hostPreview?:string};

export default async function GenericProductPage({params,searchParams}:{params:Promise<{locale:string;slug:string}>;searchParams:Promise<SearchContext>}){
 const {locale,slug}=await params,sp=await searchParams,en=locale==='en';
 const [product,allProducts]=await Promise.all([getProduct(slug),getProducts()]);if(!product)notFound();
 const ownerUserId=await resolveUserIdFromSanityProfile(product.owner?.id);
 const [productReviewSummary,publicProductReviews,ownerSummary]=await Promise.all([product.id?getProductReviewSummary(product.id):Promise.resolve(null),product.id?getPublicReviewsForProduct(product.id):Promise.resolve([]),ownerUserId?getUserReviewSummary(ownerUserId,'owner'):Promise.resolve(null)]);
 const typeLabel=en?product.typeEn??product.type:product.type,description=product.description?(en?product.description.en:product.description.sv):'',shortDescription=firstSentence(description),included=product.included??[],specs=product.specifications??[],highlight=product.cardHighlight?(en?product.cardHighlight.en:product.cardHighlight.sv):'';
 const pricing=sp.from?calculateRentalPricing(product.price,sp.from,sp.to||sp.from,product.rentalPrices,product.discounts):null,hasRentalContext=Boolean(sp.from),resultsParams=new URLSearchParams();
 const cancellationPolicy=(product.cancellationPolicy||'moderate') as CancellationPolicy,policy=CANCELLATION_POLICIES[cancellationPolicy],deadlines=sp.from?cancellationDeadlines(cancellationPolicy,sp.from,en):null;
 if(sp.q)resultsParams.set('q',sp.q);if(sp.category)resultsParams.set('category',sp.category);if(sp.from)resultsParams.set('from',sp.from);if(sp.to)resultsParams.set('to',sp.to);if(sp.place)resultsParams.set('place',sp.place);if(sp.radius)resultsParams.set('radius',sp.radius);
 const normalResultsHref=`/${locale}/produkter${resultsParams.size?`?${resultsParams.toString()}`:''}`,resultsHref=sp.hostPreview==='1'?`/${locale}/vard/annonser`:normalResultsHref,editParams=new URLSearchParams(resultsParams);editParams.set('edit','1');const editSearchHref=`/${locale}/produkter?${editParams.toString()}`;
 const responseTime=product.owner?.responseTimeMinutes ?? 60;

 return <div className="productPage2"><header className="productTopbar2"><Link href={resultsHref} className="productBack2" aria-label={sp.hostPreview==='1'?(en?'Back to listings':'Tillbaka till annonser'):(en?'Back to products':'Tillbaka till produkter')}><BackIcon/></Link><ProductPageActions slug={product.slug} title={`${product.brand} ${product.name}`} locale={locale}/></header>
 <section className="productHero2"><div className="productGallery2">{product.images?.length||product.image?<ProductGallery images={product.images?.length?product.images:[product.image!]} alt={`${product.brand} ${product.name}`} badge={product.badge} locale={locale}/>:<ProductVisual kind="cleaner" accent={product.accent}/>}</div><div className="productIdentity2"><h1><span className="productBrand2">{product.brand}</span><span className="productName2">{product.name}</span></h1><div className="productType2">{typeLabel}</div>{highlight?<div className="productHighlight2">{highlight}</div>:null}{shortDescription?<p>{shortDescription}</p>:null}{productReviewSummary?.count&&productReviewSummary.overall!=null?<div className="productRating2"><span aria-hidden="true">★</span><strong>{productReviewSummary.overall.toFixed(1).replace('.',',')}</strong><span>({productReviewSummary.count} {en?'reviews':'omdömen'})</span></div>:null}</div></section>
 {hasRentalContext&&sp.from?<><section className={styles.summaryCard} aria-label={en?'Selected rental period':'Vald hyresperiod'}><details className={styles.priceDetails}><summary style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',cursor:'pointer',listStyle:'none'}}><div><span className={styles.summaryEyebrow}>{en?'Selected dates':'Valda datum'}</span><strong className={styles.summaryDates}>{formatRentalDate(sp.from,en)}{sp.to&&sp.to!==sp.from?` – ${formatRentalDate(sp.to,en)}`:''}</strong>{sp.place?<span className={styles.summaryPlace}>{sp.place}{sp.radius?` · ${sp.radius} km`:''}</span>:null}</div>{pricing?<div style={{textAlign:'right',flex:'0 0 auto'}}><span className={styles.summaryEyebrow}>{en?'Total':'Totalt'}</span><strong className={styles.summaryTotal}>{pricing.total} kr</strong><span className={styles.summaryDetails}><span className={styles.summaryShowDetails}>{en?'Show details':'Visa detaljer'} ▾</span><span className={styles.summaryHideDetails}>{en?'Hide details':'Dölj detaljer'} ▴</span></span></div>:null}</summary>{pricing?<div className={styles.priceBreakdown}><div><span>{en?`Rental cost for ${pricing.days} ${pricing.days===1?'day':'days'}`:`Hyreskostnad för ${pricing.days} ${pricing.days===1?'dag':'dagar'}`}</span><strong>{pricing.regularRental} kr</strong></div>{pricing.discount>0?<div><span>{pricing.discountType==='repeatCustomer'?(en?`Returning customer discount ${pricing.discountPercent}%`:`Stammisrabatt ${pricing.discountPercent}%`):pricing.hasWeeklyDiscount?(en?`Weekly discount ${pricing.discountPercent}%`:`Veckorabatt ${pricing.discountPercent}%`):(en?`Multi-day discount ${pricing.discountPercent}%`:`Flerdagsrabatt ${pricing.discountPercent}%`)}</span><strong>−{pricing.discount} kr</strong></div>:null}<div><span>{en?'Booking fee':'Bokningsavgift'}</span><strong>{pricing.bookingFee} kr</strong></div><div className={styles.priceBreakdownTotal}><strong>{en?'Total':'Totalt'}</strong><strong>{pricing.total} kr</strong></div></div>:null}</details><Link href={editSearchHref} className={styles.editSearchLink}>{en?'Change search':'Ändra sökning'}</Link></section><section className="renterCancellation2"><div><span>{en?'Cancellation terms':'Avbokningsvillkor'}</span></div><p>{policySummary(cancellationPolicy,en)}</p>{deadlines?<div className="renterCancellationDeadlines2"><span>✓ {en?`Full refund until ${deadlines.full}`:`Full återbetalning till ${deadlines.full}`}</span>{deadlines.half?<span>½ {en?`50% refund until ${deadlines.half}`:`50 % återbetalning till ${deadlines.half}`}</span>:null}</div>:null}</section><BookingActions slug={product.slug} from={sp.from} to={sp.to||sp.from} locale={locale}/></>:null}

 {product.owner?.name?<section className={styles.ownerCard} aria-label={en?'About the owner':'Om uthyraren'}><div className={styles.identity}>{product.owner.profileImage?<img className={styles.avatar} src={product.owner.profileImage} alt={product.owner.name}/>:<div className={styles.avatarFallback}>{product.owner.name.slice(0,1)}</div>}<div className={styles.nameBlock}><span>{en?'Rented out by':'Uthyres av'}</span><strong>{product.owner.name}</strong><div className={styles.verified}><span className={styles.shield}><CheckIcon/></span>{en?'Verified with BankID':'Identifierad via BankID'}</div></div></div><div className={`${styles.metric} ${styles.ratingMetric}`}><span className={styles.ratingStar} aria-hidden="true">★</span><div className={styles.ratingLine}><strong>{ownerSummary?.overall!=null?ownerSummary.overall.toFixed(1).replace('.',','):'–'}</strong>{ownerSummary?.count?<span>({ownerSummary.count} {en?'reviews':'omdömen'})</span>:null}</div></div><div className={styles.metric}><span className={styles.messageIcon} aria-hidden="true">●</span><div><strong>{formatResponseTime(responseTime,en)}</strong></div></div></section>:null}

 {productReviewSummary?.count?<ReviewSummaryPanel summary={productReviewSummary} reviews={publicProductReviews} kind="product" locale={locale}/>:null}
 <section className="productSections2">{description?<details className="productAccordion2"><summary><span>{en?'Product description':'Produktbeskrivning'}</span><ForwardIcon className="productChevron2"/></summary><div className="productAccordionBody2"><p>{description}</p></div></details>:null}{included.length?<details className="productAccordion2"><summary><span>{en?'Included':'Detta ingår'}</span><ForwardIcon className="productChevron2"/></summary><div className="productAccordionBody2"><ul className="includedList2">{included.map(item=>{const text=en?item.en:item.sv;return <li key={text}><CheckIcon/><span>{text}</span></li>})}</ul></div></details>:null}{specs.length?<details className="productAccordion2"><summary><span>{en?'Specifications':'Specifikationer'}</span><ForwardIcon className="productChevron2"/></summary><div className="productAccordionBody2 productSpecs2">{specs.map(spec=><div key={spec.label.sv}><span>{en?spec.label.en:spec.label.sv}</span><strong>{spec.value}</strong></div>)}</div></details>:null}{product.guideAvailable?<Link className="productGuideRow2" href={`/${locale}/produkter/${product.slug}/guide`}><span>{en?'User guide':'Användarguide'}</span><ForwardIcon/></Link>:null}</section>
 {product.hyggloUrl?<a className="hyggloSecondaryLink2" href={product.hyggloUrl} target="_blank" rel="noreferrer">{en?'View existing listing on Hygglo':'Visa befintlig annons på Hygglo'}</a>:null}</div>
}