import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import '../../../profil/profile-menu.css';

type VacationProfile={vacation_mode_enabled:boolean|null;vacation_mode_start:string|null;vacation_mode_end:string|null};

export default async function VacationModePage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{saved?:string}>}){
  const {locale}=await params; const {saved}=await searchParams; const en=locale==='en'; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect(`/topsecret/${locale}/logga-in?next=${encodeURIComponent(`/topsecret/${locale}/vard/profil/semesterlage`)}`);
  const {data}=await supabase.from('profiles').select('vacation_mode_enabled,vacation_mode_start,vacation_mode_end').eq('id',user.id).maybeSingle() as {data:VacationProfile|null};
  async function save(formData:FormData){'use server';const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/topsecret/${locale}/logga-in`);const enabled=formData.get('enabled')==='on';const start=String(formData.get('start')||'')||null;const end=String(formData.get('end')||'')||null;if(start&&end&&end<start)redirect(`/topsecret/${locale}/vard/profil/semesterlage?error=dates`);await db.from('profiles').update({vacation_mode_enabled:enabled,vacation_mode_start:start,vacation_mode_end:end}).eq('id',user.id);redirect(`/topsecret/${locale}/vard/profil/semesterlage?saved=1`)}
  return <section className="ds2Page profileSettingsPage"><header className="profileSubHeader"><Link href={`/topsecret/${locale}/vard/profil`} aria-label={en?'Back':'Tillbaka'}>‹</Link><h1>{en?'Vacation mode':'Semesterläge'}</h1></header><p className="profileSettingsIntro">{en?'Temporarily stop new booking requests without changing existing confirmed bookings.':'Stoppa tillfälligt nya bokningsförfrågningar utan att påverka redan bekräftade bokningar.'}</p>{saved?<p role="status" className="profileSettingsIntro"><strong>{en?'Vacation mode saved.':'Semesterläget har sparats.'}</strong></p>:null}<form action={save} className="profileSettingsCard"><div className="profileSettingsCardHeading"><span>{en?'AVAILABILITY':'TILLGÄNGLIGHET'}</span><h2>{en?'Pause new rentals':'Pausa nya uthyrningar'}</h2></div><label style={{display:'flex',gap:12,alignItems:'center',margin:'18px 0'}}><input type="checkbox" name="enabled" defaultChecked={Boolean(data?.vacation_mode_enabled)}/><strong>{en?'Vacation mode active':'Semesterläge aktivt'}</strong></label><label style={{display:'grid',gap:6,margin:'14px 0'}}><span>{en?'Start date (optional)':'Startdatum (valfritt)'}</span><input type="date" name="start" defaultValue={data?.vacation_mode_start||''}/></label><label style={{display:'grid',gap:6,margin:'14px 0'}}><span>{en?'End date (optional)':'Slutdatum (valfritt)'}</span><input type="date" name="end" defaultValue={data?.vacation_mode_end||''}/></label><p>{en?'If no dates are set, vacation mode applies until you turn it off manually. Existing accepted and paid bookings remain unchanged.':'Om inga datum anges gäller semesterläget tills du stänger av det manuellt. Befintliga accepterade och betalda bokningar påverkas inte.'}</p><button type="submit" className="modeSwitchButton" style={{width:'100%',border:0}}>{en?'Save vacation mode':'Spara semesterläge'}</button></form></section>;
}