'use client';
import {useEffect,useState} from 'react';
type Cat={key:string;label:string;good:string[];bad:string[]};
const renter:Cat[]=[{key:'communication',label:'Kommunikation',good:['Snabba svar','Tydlig','Trevlig','Hjälpsam'],bad:['Långsamma svar','Otydlig','Svår att nå','Bemötande']},{key:'condition_rating',label:'Skick',good:['Som beskrivet','Välskött','Rent','Bilderna stämde'],bad:['Sämre än beskrivet','Slitet','Smutsigt','Bilderna missvisande']},{key:'function_rating',label:'Funktion',good:['Fungerade perfekt','Enkel att använda','Komplett','Bra tillbehör'],bad:['Funktionsproblem','Svår att använda','Delar saknades','Problem med tillbehör']},{key:'overall_rating',label:'Övergripande',good:['Mycket smidigt','Motsvarade förväntningarna','Skulle hyra igen','Bra helhet'],bad:['Krångligt','Under förväntan','Skulle inte hyra igen','Dålig helhet']}];
const owner:Cat[]=[{key:'communication',label:'Kommunikation',good:['Snabba svar','Tydlig','Trevlig','Lätt att nå'],bad:['Långsamma svar','Otydlig','Svår att nå','Bemötande']},{key:'handover_rating',label:'Överlämning',good:['Smidig','Punktlig','Flexibel','Följde instruktioner'],bad:['Krånglig','Försenad','Svår att koordinera','Instruktioner följdes inte']},{key:'return_condition_rating',label:'Skick vid återlämning',good:['Rent','Väl omhändertaget','Komplett','Som vid utlämning'],bad:['Smutsigt','Nytt slitage','Delar saknades','Skadat']},{key:'overall_rating',label:'Övergripande',good:['Mycket smidigt','Pålitlig','Skulle hyra ut igen','Bra helhet'],bad:['Krångligt','Under förväntan','Skulle inte hyra ut igen','Dålig helhet']}];
const tagKey=(k:string)=>k==='communication'?'communication_tags':k==='condition_rating'?'condition_tags':k==='function_rating'?'function_tags':k==='handover_rating'?'handover_tags':k==='return_condition_rating'?'return_condition_tags':'';
export default function BookingReviewFlow({bookingId,isOwner}:{bookingId:string;isOwner:boolean}){const [state,setState]=useState<any>(null),[ratings,setRatings]=useState<Record<string,number>>({}),[tags,setTags]=useState<Record<string,string[]>>({}),[person,setPerson]=useState<boolean|null>(null),[product,setProduct]=useState<boolean|null>(null),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); const cats=isOwner?owner:renter;
 useEffect(()=>{fetch(`/api/bookings/${bookingId}/reviews`).then(r=>r.json()).then(setState)},[bookingId]); if(!state||(!state.eligible&&!state.submitted&&!state.revealed?.length))return null;
 if(state.submitted&&!state.revealed?.length)return <section className="reviewBox"><span>OMDÖME</span><h2>Tack för ditt omdöme</h2><p>Det är dolt tills den andra personen också har lämnat sitt omdöme eller 7-dagarsperioden löper ut.</p></section>;
 if(state.revealed?.length)return <section className="reviewBox"><span>OMDÖMEN</span><h2>Omdömena är publicerade</h2><p>Båda omdömena är nu synliga eftersom båda har svarat eller recensionsperioden har löpt ut.</p></section>;
 const low=cats.some(c=>(ratings[c.key]||5)<=3); const complete=cats.every(c=>ratings[c.key])&&person!==null&&(isOwner||product!==null)&&(!low||comment.trim().length>=10);
 const toggle=(k:string,t:string)=>setTags(x=>({...x,[k]:(x[k]||[]).includes(t)?(x[k]||[]).filter(v=>v!==t):[...(x[k]||[]),t]}));
 async function submit(){if(!complete)return;setBusy(true);setError('');const body:any={...ratings,recommend_person:person,recommend_product:isOwner?undefined:product,comment};cats.forEach(c=>{const k=tagKey(c.key);if(k)body[k]=tags[c.key]||[]});const r=await fetch(`/api/bookings/${bookingId}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(r.ok)setState({...state,eligible:false,submitted:true});else setError(j.error==='COMMENT_REQUIRED'?'Skriv minst en kort förklaring när något betyg är 1–3.':'Omdömet kunde inte sparas.');setBusy(false)}
 return <section className="reviewBox"><span>7 DAGAR ATT SVARA</span><h2>Hur gick uthyrningen?</h2><p>Ditt omdöme är dubbelblint. Motparten ser inget förrän båda har svarat eller perioden löpt ut.</p>{cats.map(c=>{const n=ratings[c.key];const opts=n?(n>=4?c.good:c.bad):[];return <div className="reviewCategory" key={c.key}><strong>{c.label}</strong><div className="reviewStars">{[1,2,3,4,5].map(v=><button key={v} className={n>=v?'on':''} onClick={()=>setRatings(x=>({...x,[c.key]:v}))} aria-label={`${v} av 5`}>★</button>)}</div>{n?<><small>{['','Mycket dåligt','Dåligt','Okej','Bra','Utmärkt'][n]}</small><div className="reviewTags">{opts.map(t=><button key={t} className={(tags[c.key]||[]).includes(t)?'selected':''} onClick={()=>toggle(c.key,t)}>{t}</button>)}</div></>:null}</div>})}<div className="reviewRecommend"><strong>Skulle du rekommendera {isOwner?'hyrestagaren':'uthyraren'} till andra?</strong><div><button className={person===true?'selected':''} onClick={()=>setPerson(true)}>Ja</button><button className={person===false?'selected':''} onClick={()=>setPerson(false)}>Nej</button></div></div>{!isOwner?<div className="reviewRecommend"><strong>Skulle du rekommendera produkten till andra?</strong><div><button className={product===true?'selected':''} onClick={()=>setProduct(true)}>Ja</button><button className={product===false?'selected':''} onClick={()=>setProduct(false)}>Nej</button></div></div>:null}<label className="reviewComment"><strong>{low?'Berätta vad som kunde varit bättre *':'Vill du lägga till något?'}</strong><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder={low?'Minst 10 tecken krävs när något betyg är 1–3.':'Frivillig kommentar'}/></label>{error?<p className="reviewError">{error}</p>:null}<button className="reviewSubmit" disabled={!complete||busy} onClick={submit}>{busy?'Skickar…':'Skicka omdöme'}</button></section>}
