'use client';
import{useState}from'react';import{useRouter}from'next/navigation';

const renterReasons=['Planerna ändrades','Behöver inte produkten längre','Problem med tid eller plats','Hittade ett annat alternativ','Annat'];
const ownerReasons=['Produkten är inte tillgänglig','Problem med utlämningen','Produkten behöver repareras','Kan inte genomföra uthyrningen','Annat'];

export default function BookingCancellationFlow({bookingId,status,isOwner,totalPrice,locale}:{bookingId:string;status:string;isOwner:boolean;totalPrice:number;locale:string}){
 const en=locale==='en',r=useRouter(),[open,setOpen]=useState(false),[reason,setReason]=useState(''),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const canCancel=isOwner?['accepted','paid'].includes(status):['requested','reserved','accepted','paid'].includes(status);if(!canCancel)return null;
 const paid=status==='paid',reasons=isOwner?ownerReasons:renterReasons;const valid=Boolean(reason)&&(reason!=='Annat'||details.trim().length>=10);
 async function submit(){if(!valid)return;setBusy(true);setError('');const x=await fetch(`/api/bookings/${bookingId}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason,details})});const j=await x.json();if(x.ok){setOpen(false);window.dispatchEvent(new Event('hyrbart:bookings-changed'));r.refresh()}else setError(j.error==='DETAILS_REQUIRED'?(en?'Please add a short explanation.':'Skriv en kort förklaring.'):(en?'Could not cancel the booking.':'Bokningen kunde inte avbokas.'));setBusy(false)}
 return <section className="bookingCancellationCard"><button className="bookingCancelTrigger" onClick={()=>setOpen(x=>!x)}>{open?(en?'Keep booking':'Behåll bokningen'):(en?'Cancel booking':'Avboka bokning')}</button>{open?<div className="bookingCancellationBody"><span>{en?'CANCELLATION':'AVBOKNING'}</span><h3>{en?'Why are you cancelling?':'Varför avbokar du?'}</h3><p>{isOwner?(en?'The renter will be notified immediately.':'Hyrestagaren meddelas direkt.'):(en?'The owner will be notified immediately.':'Uthyraren meddelas direkt.')}</p><div className="bookingCancellationReasons">{reasons.map(x=><button key={x} className={reason===x?'selected':''} onClick={()=>setReason(x)}>{x}</button>)}</div>{reason?<label>{en?'Anything else?':'Vill du lägga till något?'}<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder={reason==='Annat'?(en?'At least 10 characters':'Minst 10 tecken'):(en?'Optional':'Frivilligt')}/></label>:null}<div className="bookingCancellationSummary"><strong>{paid?(en?'Refund':'Återbetalning'):(en?'Payment':'Betalning')}</strong><span>{paid?(en?`${totalPrice.toLocaleString('en-GB')} SEK will be marked for full refund in test mode.`:`${totalPrice.toLocaleString('sv-SE')} kr markeras för full återbetalning i testläget.`):(en?'No payment has been made.':'Ingen betalning har genomförts.')}</span><small>{en?'The dates are released when the cancellation is completed.':'Datumen blir tillgängliga igen när avbokningen genomförs.'}</small></div>{error?<em>{error}</em>:null}<button className="bookingCancellationConfirm" disabled={!valid||busy} onClick={submit}>{busy?(en?'Cancelling…':'Avbokar…'):(en?'Confirm cancellation':'Bekräfta avbokning')}</button></div>:null}</section>
}
