'use client';

import { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { SearchIcon } from './Icons';

type Props={locale:string;initialQuery?:string;category?:string;initialFrom?:string;initialTo?:string;initialPlace?:string;initialRadius?:string;initiallyCollapsed?:boolean};
type ProductSuggestion={label:string;kind:'type'|'product'|'category'};
type LocationSuggestion={label:string;lat:number;lng:number;type:string};
type RecentSearch={q?:string;from?:string;to?:string;place?:string;radius?:string;ts?:number};
type ActiveStep='what'|'when'|'where'|null;
const RECENT_SEARCHES_KEY='hyrbartRecentSearches';
function compactDate(value:string,en:boolean){if(!value)return'';return new Intl.DateTimeFormat(en?'en-GB':'sv-SE',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`))}
function isoDate(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}
function monthCells(cursor:Date){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();return Array.from({length:offset+days},(_,i)=>{const d=i-offset+1;return d>=1&&d<=days?new Date(y,m,d):null})}
function BackIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 18l-6-6 6-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function LocationIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11Z" fill="none" stroke="currentColor" strokeWidth="1.8"/><circle cx="12" cy="10" r="2.1" fill="currentColor"/></svg>}

export default function ProductSearchForm({locale,initialQuery='',category,initialFrom='',initialTo='',initialPlace='',initialRadius='10',initiallyCollapsed=false}:Props){
 const router=useRouter(),en=locale==='en';
 const formRef=useRef<HTMLFormElement>(null),queryInputRef=useRef<HTMLInputElement>(null),placeInputRef=useRef<HTMLInputElement>(null),calendarScrollRef=useRef<HTMLDivElement>(null);
 const [expanded,setExpanded]=useState(!initiallyCollapsed),[activeStep,setActiveStep]=useState<ActiveStep>(null);
 const [query,setQuery]=useState(initialQuery),[from,setFrom]=useState(initialFrom),[to,setTo]=useState(initialTo),[place,setPlace]=useState(initialPlace),[radius,setRadius]=useState(initialRadius);
 const [searchStarted,setSearchStarted]=useState(Boolean(initialQuery.trim()||initialFrom||initialTo||initiallyCollapsed));
 const [recentSearches,setRecentSearches]=useState<RecentSearch[]>([]);
 const [productSuggestions,setProductSuggestions]=useState<ProductSuggestion[]>([]),[showProductSuggestions,setShowProductSuggestions]=useState(false);
 const [locationSuggestions,setLocationSuggestions]=useState<LocationSuggestion[]>([]),[showLocationSuggestions,setShowLocationSuggestions]=useState(false),[locating,setLocating]=useState(false);

 useEffect(()=>{try{const parsed=JSON.parse(window.localStorage.getItem(RECENT_SEARCHES_KEY)||'[]');if(Array.isArray(parsed))setRecentSearches(parsed.slice(0,5))}catch{setRecentSearches([])}},[]);
 useEffect(()=>{if(!searchStarted)return;function outside(event:PointerEvent){if(formRef.current&&!formRef.current.contains(event.target as Node)){setActiveStep(null);setShowProductSuggestions(false);setShowLocationSuggestions(false)}}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[searchStarted]);
 useEffect(()=>{const q=query.trim();if(!q){setProductSuggestions([]);return}const controller=new AbortController();const timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/product-suggestions?q=${encodeURIComponent(q)}`,{signal:controller.signal});const data=await response.json() as {results?:ProductSuggestion[]};setProductSuggestions(data.results??[])}catch{}},180);return()=>{window.clearTimeout(timer);controller.abort()}},[query]);
 useEffect(()=>{const q=place.trim();if(q.length<2){setLocationSuggestions([]);return}const controller=new AbortController();const timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/location-search?q=${encodeURIComponent(q)}`,{signal:controller.signal});const data=await response.json() as {results?:LocationSuggestion[]};setLocationSuggestions(data.results??[])}catch{}},260);return()=>{window.clearTimeout(timer);controller.abort()}},[place]);

 const today=isoDate(new Date());
 const baseMonth=useMemo(()=>{const source=initialFrom?new Date(`${initialFrom}T12:00:00`):new Date();return new Date(source.getFullYear(),source.getMonth(),1)},[initialFrom]);
 const months=useMemo(()=>Array.from({length:12},(_,i)=>new Date(baseMonth.getFullYear(),baseMonth.getMonth()+i,1)),[baseMonth]);
 const weekdays=en?['M','T','W','T','F','S','S']:['M','T','O','T','F','L','S'];
 const hasActiveFilters=Boolean(query||from||to||category||place||radius!=='10');
 function rememberSearch(search:RecentSearch){try{const normalized={q:search.q?.trim()||'',from:search.from||'',to:search.to||'',place:search.place?.trim()||'',radius:search.radius||'10',ts:Date.now()},key=`${normalized.q}|${normalized.from}|${normalized.to}|${normalized.place}|${normalized.radius}`;const parsed=JSON.parse(window.localStorage.getItem(RECENT_SEARCHES_KEY)||'[]'),list=Array.isArray(parsed)?parsed:[];const next=[normalized,...list.filter(item=>`${item?.q||''}|${item?.from||''}|${item?.to||''}|${item?.place||''}|${item?.radius||'10'}`!==key)].slice(0,5);window.localStorage.setItem(RECENT_SEARCHES_KEY,JSON.stringify(next));setRecentSearches(next)}catch{}}
 function navigate(next:{query?:string;from?:string;to?:string;place?:string;radius?:string}={},collapse=true){const qv=next.query??query,fv=next.from??from,tv=next.to??to,pv=next.place??place,rv=next.radius??radius,params=new URLSearchParams();if(qv.trim())params.set('q',qv.trim());if(category)params.set('category',category);if(fv)params.set('from',fv);if(tv)params.set('to',tv);if(pv.trim())params.set('place',pv.trim());if(rv)params.set('radius',rv);if(collapse){rememberSearch({q:qv,from:fv,to:tv||fv,place:pv,radius:rv});setActiveStep(null);setExpanded(false);window.scrollTo(0,0)}router.push(`/${locale}/produkter?${params.toString()}`,{scroll:collapse})}
 function resetSearch(){setQuery('');setFrom('');setTo('');setPlace('');setRadius('10');setActiveStep('what');setShowProductSuggestions(true);setShowLocationSuggestions(false);setExpanded(true);setSearchStarted(true);router.push(`/${locale}`,{scroll:false});requestAnimationFrame(()=>queryInputRef.current?.focus())}
 function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(searchStarted)navigate()}
 function activateWhat(){setSearchStarted(true);setActiveStep('what');setShowProductSuggestions(true);setShowLocationSuggestions(false)}
 function openCalendar(){setSearchStarted(true);setActiveStep('when');setShowProductSuggestions(false);setShowLocationSuggestions(false);requestAnimationFrame(()=>calendarScrollRef.current?.scrollTo({top:0,behavior:'smooth'}))}
 function openWhere(){setSearchStarted(true);setActiveStep('where');setShowProductSuggestions(false);setShowLocationSuggestions(true);requestAnimationFrame(()=>{placeInputRef.current?.focus();placeInputRef.current?.select()})}
 function queryKeyDown(event:KeyboardEvent<HTMLInputElement>){if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur();openCalendar()}}
 function pickProduct(label:string){setQuery(label);openCalendar()}
 function pickRecent(item:RecentSearch){setQuery(item.q||'');setFrom(item.from||'');setTo(item.to||'');setPlace(item.place||'');setRadius(item.radius||'10');openCalendar()}
 function nextFromCalendar(){if(!from)return;if(!to)setTo(from);openWhere()}
 function chooseDate(value:string){if(value<today)return;if(!from||to){setFrom(value);setTo('')}else if(value<from){setFrom(value);setTo('')}else setTo(value)}
 function placeKeyDown(event:KeyboardEvent<HTMLInputElement>){if(event.key==='Enter'){event.preventDefault();setShowLocationSuggestions(false);navigate()}}
 function useCurrentLocation(){if(!navigator.geolocation)return;setLocating(true);navigator.geolocation.getCurrentPosition(async position=>{try{const response=await fetch(`/api/reverse-geocode?lat=${position.coords.latitude}&lng=${position.coords.longitude}`);const data=await response.json() as {label?:string};if(data.label){setPlace(data.label);setShowLocationSuggestions(false)}}finally{setLocating(false)}},()=>setLocating(false),{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
 const dateLabel=from?(to?`${compactDate(from,en)} – ${compactDate(to,en)}`:compactDate(from,en)):(en?'When do you need it?':'När behöver du det?');
 const whatLabel=query||(en?'All products':'Alla produkter'),whereLabel=place?`${place} · ${radius} km`:(en?'Where do you need it?':'Var behöver du det?');
 const recentMeta=(item:RecentSearch)=>[item.from?(item.to&&item.to!==item.from?`${compactDate(item.from,en)} – ${compactDate(item.to,en)}`:compactDate(item.from,en)):'',item.place].filter(Boolean).join(' · ');
 if(!expanded)return <button type="button" className="rentalSearchCompact2" onClick={()=>{setExpanded(true);setSearchStarted(true);requestAnimationFrame(()=>queryInputRef.current?.focus())}} aria-label={en?'Edit search':'Ändra sökning'}><SearchIcon/><span><b>{whatLabel}</b><small>{dateLabel} · {whereLabel}</small></span><span className="rentalSearchEdit2">☰</span></button>;
 return <form ref={formRef} onSubmit={handleSubmit} className={`rentalSearchFlow2 ${activeStep==='when'?'calendarIsOpen':''}`}>
  <div className={`rentalSearchSection2 whatSection2 ${activeStep==='what'?'active':''}`}><label className="rentalSearchField2 rentalWhatField2"><button type="button" className="rentalLeadingIcon2" onClick={()=>activeStep==='what'?(setActiveStep(null),setShowProductSuggestions(false),queryInputRef.current?.blur()):activateWhat()} aria-label={activeStep==='what'?(en?'Back':'Tillbaka'):(en?'Search':'Sök')}>{activeStep==='what'?<BackIcon/>:<SearchIcon/>}</button><span>{activeStep==='what'&&<b>{en?'What':'Vad'}</b>}<input ref={queryInputRef} value={query} onFocus={activateWhat} onChange={e=>{setQuery(e.target.value);setShowProductSuggestions(true)}} onKeyDown={queryKeyDown} enterKeyHint="next" autoComplete="off" placeholder={activeStep==='what'?(en?'Search rental items':'Sök hyresobjekt'):(en?'What do you need?':'Vad behöver du?')}/></span></label>
   {activeStep==='what'&&showProductSuggestions&&<div className="searchSuggestMenu2 whatSuggestMenu2" role="listbox">{query.trim()&&productSuggestions.map(item=><button type="button" className="searchSuggestItem2" key={`${item.kind}-${item.label}`} onPointerDown={e=>e.preventDefault()} onClick={()=>pickProduct(item.label)}><span>{item.label}</span><small>{item.kind==='product'?(en?'product':'produkt'):item.kind==='category'?(en?'category':'kategori'):(en?'type':'typ')}</small></button>)}{!query.trim()&&recentSearches.length>0&&<><div className="searchSuggestHeading2">{en?'Recent searches':'Senaste sökningar'}</div>{recentSearches.map((item,index)=><button type="button" className="searchSuggestItem2 recentSuggestItem2" key={`${item.ts||index}-${item.q||''}`} onPointerDown={e=>e.preventDefault()} onClick={()=>pickRecent(item)}><span><b>{item.q||(en?'All products':'Alla produkter')}</b>{recentMeta(item)&&<small>{recentMeta(item)}</small>}</span><SearchIcon/></button>)}</>}</div>}
  </div>
  {searchStarted&&<><div className="rentalWhenWrap2"><button type="button" className={`rentalSearchRow2 ${activeStep==='when'?'active':''}`} onClick={openCalendar}><span><b>{en?'When':'När'}</b><small>{dateLabel}</small></span><span className="rentalPlus2">＋</span></button>{activeStep==='when'&&<div className="rentalCalendar2 rentalCalendarOverlay2"><div className="rentalCalendarScroll2" ref={calendarScrollRef}>{months.map((month,monthIndex)=>{const label=new Intl.DateTimeFormat(en?'en-GB':'sv-SE',{month:'long',year:'numeric'}).format(month),cells=monthCells(month);return <section className="rentalCalendarMonth2" key={`${month.getFullYear()}-${month.getMonth()}`}><strong className="rentalCalendarMonthTitle2">{label}</strong>{monthIndex===0&&<div className="rentalWeekdays2">{weekdays.map((d,i)=><span key={`${d}-${i}`}>{d}</span>)}</div>}<div className="rentalCalendarGrid2">{cells.map((date,i)=>{if(!date)return <span key={`blank-${monthIndex}-${i}`}/>;const value=isoDate(date),disabled=value<today,start=value===from,end=value===to,inRange=Boolean(from&&to&&value>from&&value<to);return <button type="button" key={value} disabled={disabled} className={`${start||end?'selected':''} ${inRange?'inRange':''}`} onClick={()=>chooseDate(value)}>{date.getDate()}</button>})}</div></section>})}</div><div className="rentalCalendarFooter2"><button type="button" className="clear" onClick={()=>{setFrom('');setTo('')}}>{en?'Clear':'Rensa'}</button><button type="button" className="done" disabled={!from} onClick={nextFromCalendar}>{en?'Next':'Nästa'}</button></div></div>}</div>
   <div className="rentalWhereWrap2"><label className={`rentalSearchField2 rentalWhereField2 ${activeStep==='where'?'active':''}`}><span><b>{en?'Where':'Var'}</b><input ref={placeInputRef} value={place} onFocus={openWhere} onChange={e=>{setPlace(e.target.value);setShowLocationSuggestions(true)}} onKeyDown={placeKeyDown} enterKeyHint="search" autoComplete="street-address" placeholder={en?'Search a place':'Sök plats'}/></span><span className="rentalRadiusInline2"><small>{radius} km</small><input aria-label={en?'Search radius':'Sökradie'} type="range" min="1" max="50" step="1" value={radius} onChange={e=>setRadius(e.target.value)}/></span></label>{activeStep==='where'&&showLocationSuggestions&&<div className="searchSuggestMenu2 locationSuggestMenu2" role="listbox"><button type="button" className="searchSuggestItem2 nearbySuggestItem2" disabled={locating} onPointerDown={e=>e.preventDefault()} onClick={useCurrentLocation}><span className="locationSuggestIcon2"><LocationIcon/></span><span><b>{locating?(en?'Locating…':'Hämtar position…'):(en?'Nearby':'I närheten')}</b><small>{en?'Find everything available nearby':'Hitta allt som finns i närheten'}</small></span></button>{locationSuggestions.map(item=><button type="button" className="searchSuggestItem2" key={`${item.lat}-${item.lng}`} onPointerDown={e=>e.preventDefault()} onClick={()=>{setPlace(item.label);setShowLocationSuggestions(false)}}><span>{item.label}</span></button>)}</div>}</div>
   <div className="rentalSearchActions2">{hasActiveFilters&&<button type="button" className="rentalSearchReset2" onClick={resetSearch}>{en?'Clear filters':'Rensa filter'}</button>}<button type="submit" className="rentalSearchSubmit2"><SearchIcon/>{en?'Search':'Sök'}</button></div></>}
 </form>
}
