'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import ProductVisual from './ProductVisual';
import { ProductBadgeLabel } from './ProductPricing';

type GeoPoint={lat:number;lng:number};
type ResultItem={slug:string;href:string;brand:string;name:string;type:string;image?:string;accent?:string;badge?:'popular'|'very-popular';priceLabel:string;mapLabel:string;lat?:number;lng?:number;distanceKm?:number};
type LeafletLike={map:(node:HTMLElement,options?:Record<string,unknown>)=>any;tileLayer:(url:string,options?:Record<string,unknown>)=>any;marker:(latlng:[number,number],options?:Record<string,unknown>)=>any;divIcon:(options?:Record<string,unknown>)=>any};
declare global{interface Window{L?:LeafletLike}}
function zoomForRadius(radius:number){if(radius<=3)return 14;if(radius<=7)return 13;if(radius<=15)return 12;if(radius<=30)return 11;return 10}
function escapeHtml(value:string){return value.replace(/[&<>'\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[char]??char))}

export default function SearchResults({locale,place,radius,center,items,metaLabel}:{locale:string;place:string;radius:number;center:GeoPoint;items:ResultItem[];metaLabel:string}){
 const en=locale==='en';
 const [activeSlug,setActiveSlug]=useState<string|null>(items[0]?.slug??null);
 const cardRefs=useRef<Record<string,HTMLAnchorElement|null>>({}),mapNodeRef=useRef<HTMLDivElement|null>(null),mapInstanceRef=useRef<any>(null),markerLayerRef=useRef<any[]>([]);
 const zoom=zoomForRadius(radius);
 const markerGroups=useMemo(()=>{const groups=new Map<string,ResultItem[]>();items.forEach(item=>{if(item.lat==null||item.lng==null)return;const key=`${item.lat.toFixed(5)},${item.lng.toFixed(5)}`,group=groups.get(key)??[];group.push(item);groups.set(key,group)});return Array.from(groups.values())},[items]);
 function chooseMarker(slug:string){setActiveSlug(slug);requestAnimationFrame(()=>cardRefs.current[slug]?.scrollIntoView({behavior:'smooth',block:'center'}))}
 useEffect(()=>{const cssId='leaflet-css-hyrbart';if(!document.getElementById(cssId)){const link=document.createElement('link');link.id=cssId;link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(link)}function initialiseMap(){const L=window.L,node=mapNodeRef.current;if(!L||!node||mapInstanceRef.current)return;const map=L.map(node,{zoomControl:true,attributionControl:true,dragging:true,scrollWheelZoom:true,doubleClickZoom:true,touchZoom:true});map.setView([center.lat,center.lng],zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);mapInstanceRef.current=map;setTimeout(()=>map.invalidateSize(),0)}if(window.L)initialiseMap();else{const existing=document.getElementById('leaflet-js-hyrbart') as HTMLScriptElement|null;if(existing)existing.addEventListener('load',initialiseMap,{once:true});else{const script=document.createElement('script');script.id='leaflet-js-hyrbart';script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.async=true;script.onload=initialiseMap;document.body.appendChild(script)}}return()=>{if(mapInstanceRef.current){mapInstanceRef.current.remove();mapInstanceRef.current=null;markerLayerRef.current=[]}}},[center.lat,center.lng,zoom]);
 useEffect(()=>{const L=window.L,map=mapInstanceRef.current;if(!L||!map)return;markerLayerRef.current.forEach(marker=>marker.remove());markerLayerRef.current=[];markerGroups.forEach(group=>{const first=group[0];if(first.lat==null||first.lng==null)return;const active=group.some(item=>item.slug===activeSlug),label=`${escapeHtml(first.mapLabel)}${group.length>1?` · ${group.length}`:''}`,icon=L.divIcon({className:'hyrbartLeafletIcon2',html:`<span class="mapPrice2 leafletPrice2${active?' active':''}">${label}</span>`,iconSize:undefined,iconAnchor:undefined}),marker=L.marker([first.lat,first.lng],{icon}).addTo(map);marker.on('click',()=>chooseMarker(first.slug));markerLayerRef.current.push(marker)})},[markerGroups,activeSlug]);
 return <><section className="resultsMap2" aria-label={en?'Map of search results':'Karta över sökresultat'}><div ref={mapNodeRef} className="resultsLeafletMap2"/><span className="mapAreaNotice2">{radius} km · {place}</span></section><div className="rentMeta2 searchResultsMeta2"><span>{metaLabel}</span></div><section className="productGrid2">{items.map(item=><Link ref={node=>{cardRefs.current[item.slug]=node}} href={item.href} className={`productTile2 searchResultTile2${activeSlug===item.slug?' active':''}`} key={item.slug} onFocus={()=>setActiveSlug(item.slug)} onMouseEnter={()=>setActiveSlug(item.slug)} onTouchStart={()=>setActiveSlug(item.slug)}><div className="productTileVisual2"><ProductVisual kind="cleaner" accent={item.accent} imageSrc={item.image} imageAlt={`${item.brand} ${item.name}`}/><ProductBadgeLabel badge={item.badge} locale={locale}/></div><div className="productTileCopy2"><strong>{item.brand} {item.name}</strong><span>{item.type}</span>{item.distanceKm!=null?<span className="productDistance2">{item.distanceKm<.1?(en?'< 0.1 km away':'< 0,1 km bort'):`${item.distanceKm.toLocaleString(en?'en-GB':'sv-SE',{maximumFractionDigits:1})} km ${en?'away':'bort'}`}</span>:null}<b>{item.priceLabel}</b></div></Link>)}</section></>
}
