'use client';

import Link from 'next/link';
import { type CSSProperties, useEffect, useState } from 'react';

type Alert = {
  id:string; status:'active'|'paused'|'expired'; query_text:string|null; category:string|null; place:string|null; radius_km:number;
  start_date:string; end_date:string; max_total_price:number|null; min_rating:number|null; discount_only:boolean; locale:'sv'|'en';
  notification_channel:'in_app'|'in_app_push'; last_evaluated_at:string|null;
};

function searchHref(alert:Alert,locale:string){const p=new URLSearchParams();if(alert.query_text)p.set('q',alert.query_text);if(alert.category)p.set('category',alert.category);p.set('from',alert.start_date);p.set('to',alert.end_date);if(alert.place)p.set('place',alert.place);p.set('radius',String(alert.radius_km));if(alert.max_total_price!=null)p.set('maxPrice',String(alert.max_total_price));if(alert.min_rating!=null)p.set('minRating',String(alert.min_rating));if(alert.discount_only)p.set('discountOnly','1');return `/${locale}/produkter?${p.toString()}`}

export default function SearchAlertsManager({locale}:{locale:string}){
 const en=locale==='en';
 const [alerts,setAlerts]=useState<Alert[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/search-alerts',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json() as {alerts?:Alert[]};setAlerts(d.alerts||[])}catch{setError(en?'Could not load watches.':'Kunde inte ladda bevakningar.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function patch(id:string,body:Record<string,unknown>){setBusy(id);setError('');try{const r=await fetch('/api/search-alerts',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...body})});const d=await r.json().catch(()=>({})) as {alert?:Alert;error?:string};if(!r.ok||!d.alert)throw new Error(d.error||'SAVE_FAILED');setAlerts(current=>current.map(item=>item.id===id?d.alert!:item));setEditing(null)}catch{setError(en?'Could not save the watch.':'Kunde inte spara bevakningen.')}finally{setBusy(null)}}
 async function remove(id:string){if(!window.confirm(en?'Delete this watch?':'Ta bort den här bevakningen?'))return;setBusy(id);try{const r=await fetch('/api/search-alerts',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw new Error();setAlerts(current=>current.filter(item=>item.id!==id))}catch{setError(en?'Could not delete the watch.':'Kunde inte ta bort bevakningen.')}finally{setBusy(null)}}
 if(loading)return <p className="ds2Intro">{en?'Loading watches…':'Laddar bevakningar…'}</p>;
 return <div style={{display:'grid',gap:14}}>
   {error?<p role="alert" style={{color:'#9b1c1c'}}>{error}</p>:null}
   {!alerts.length?<section style={{padding:22,border:'1px solid var(--line)',borderRadius:18,background:'#fff'}}><h2 style={{marginTop:0}}>{en?'No watches yet':'Inga bevakningar ännu'}</h2><p style={{color:'var(--muted)'}}>{en?'When a search has few or no available results, you can save it as a watch.':'När en sökning har få eller inga lediga träffar kan du spara den som en bevakning.'}</p><Link href={`/${locale}/produkter`}>{en?'Search rentals':'Sök hyresobjekt'} →</Link></section>:null}
   {alerts.map(alert=><section key={alert.id} style={{padding:18,border:'1px solid var(--line)',borderRadius:18,background:'#fff',opacity:alert.status==='expired'?.68:1}}>
     <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><small style={{color:'var(--muted)',textTransform:'uppercase',fontWeight:800}}>{alert.status==='active'?(en?'Active':'Aktiv'):alert.status==='paused'?(en?'Paused':'Pausad'):(en?'Expired':'Utgången')}</small><h2 style={{margin:'4px 0 3px',fontSize:'1.08rem'}}>{alert.query_text||alert.category|| (en?'Saved search':'Sparad sökning')}</h2><p style={{margin:0,color:'var(--muted)'}}>{alert.place?`${alert.place} · `:''}${alert.radius_km} km · {alert.start_date}{alert.end_date!==alert.start_date?` – ${alert.end_date}`:''}</p></div><strong>{alert.max_total_price!=null?(en?`Max SEK ${alert.max_total_price}`:`Max ${alert.max_total_price} kr`):(en?'No price limit':'Inget maxpris')}</strong></div>
     {editing===alert.id?<EditForm alert={alert} en={en} disabled={busy===alert.id} onCancel={()=>setEditing(null)} onSave={body=>void patch(alert.id,body)}/>:<>
       <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}><Link href={searchHref(alert,locale)} style={buttonStyle}>{en?'Open search':'Öppna sökning'}</Link>{alert.status!=='expired'?<button type="button" style={buttonStyle} onClick={()=>setEditing(alert.id)}>{en?'Edit':'Ändra'}</button>:null}{alert.status!=='expired'?<button type="button" disabled={busy===alert.id} style={buttonStyle} onClick={()=>void patch(alert.id,{status:alert.status==='active'?'paused':'active'})}>{alert.status==='active'?(en?'Pause':'Pausa'):(en?'Resume':'Återuppta')}</button>:null}<button type="button" disabled={busy===alert.id} style={{...buttonStyle,color:'#9b1c1c'}} onClick={()=>void remove(alert.id)}>{en?'Delete':'Ta bort'}</button></div>
       <p style={{fontSize:12,color:'var(--muted)',margin:'10px 0 0'}}>{alert.min_rating!=null?`★ ${alert.min_rating}+ · `:''}{alert.discount_only?(en?'Discount required · ':'Rabatt krävs · '):''}{alert.notification_channel==='in_app_push'?(en?'Notification centre + Web Push':'Notiscenter + Web Push'):(en?'Notification centre':'Notiscenter')}{alert.last_evaluated_at?` · ${en?'Last checked':'Senast kontrollerad'} ${new Date(alert.last_evaluated_at).toLocaleString(en?'en-GB':'sv-SE')}`:''}</p>
     </>}
   </section>)}
 </div>
}

const buttonStyle:CSSProperties={display:'inline-flex',alignItems:'center',justifyContent:'center',minHeight:40,padding:'0 12px',border:'1px solid var(--line)',borderRadius:11,background:'#fff',color:'var(--ink)',fontWeight:750,textDecoration:'none',cursor:'pointer'};

function EditForm({alert,en,disabled,onCancel,onSave}:{alert:Alert;en:boolean;disabled:boolean;onCancel:()=>void;onSave:(body:Record<string,unknown>)=>void}){
 const [q,setQ]=useState(alert.query_text||''),[category,setCategory]=useState(alert.category||''),[place,setPlace]=useState(alert.place||''),[radius,setRadius]=useState(String(alert.radius_km)),[from,setFrom]=useState(alert.start_date),[to,setTo]=useState(alert.end_date),[price,setPrice]=useState(alert.max_total_price==null?'':String(alert.max_total_price)),[minRating,setMinRating]=useState(alert.min_rating==null?'':String(alert.min_rating)),[discountOnly,setDiscountOnly]=useState(alert.discount_only),[channel,setChannel]=useState(alert.notification_channel);
 return <div style={{display:'grid',gap:10,marginTop:16,paddingTop:14,borderTop:'1px solid var(--line)'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}><label>{en?'Search term':'Sökord'}<input value={q} onChange={e=>setQ(e.target.value)} style={inputStyle}/></label><label>{en?'Category':'Kategori'}<input value={category} onChange={e=>setCategory(e.target.value)} style={inputStyle}/></label><label>{en?'Place':'Plats'}<input value={place} onChange={e=>setPlace(e.target.value)} style={inputStyle}/></label><label>{en?'Radius':'Radie'}<select value={radius} onChange={e=>setRadius(e.target.value)} style={inputStyle}>{[2,5,10,25,50].map(v=><option key={v} value={v}>{v} km</option>)}</select></label><label>{en?'From':'Från'}<input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={inputStyle}/></label><label>{en?'To':'Till'}<input type="date" value={to} onChange={e=>setTo(e.target.value)} style={inputStyle}/></label><label>{en?'Max total price':'Max totalpris'}<input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} style={inputStyle}/></label><label>{en?'Minimum rating':'Minsta betyg'}<select value={minRating} onChange={e=>setMinRating(e.target.value)} style={inputStyle}><option value="">{en?'Any':'Alla'}</option><option value="4">4,0+</option><option value="4.5">4,5+</option></select></label><label>{en?'Notification':'Notifiering'}<select value={channel} onChange={e=>setChannel(e.target.value as Alert['notification_channel'])} style={inputStyle}><option value="in_app_push">{en?'Centre + Push':'Center + Push'}</option><option value="in_app">{en?'Centre only':'Endast center'}</option></select></label><label style={{display:'flex',alignItems:'center',gap:8,paddingTop:24}}><input type="checkbox" checked={discountOnly} onChange={e=>setDiscountOnly(e.target.checked)}/><span>{en?'Discount required':'Rabatt krävs'}</span></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8}}><button type="button" style={buttonStyle} onClick={onCancel}>{en?'Cancel':'Avbryt'}</button><button type="button" disabled={disabled} style={{...buttonStyle,background:'var(--accent)',borderColor:'var(--accent)',color:'#111'}} onClick={()=>onSave({query:q,category,place,radius,from,to,maxPrice:price,minRating,discountOnly,notificationChannel:channel})}>{disabled?(en?'Saving…':'Sparar…'):(en?'Save':'Spara')}</button></div></div>
}
const inputStyle:CSSProperties={display:'block',width:'100%',minHeight:40,marginTop:5,border:'1px solid var(--line)',borderRadius:10,padding:'0 9px',background:'#fff'};
