import Link from 'next/link';
import { getProducts, getUnavailableProductSlugs } from '@/lib/sanity-products';
import { getUnavailableProductIds } from '@/lib/supabase-bookings';
import { getProductReviewSummaries } from '@/lib/review-summaries';
import { distanceKm, geocodeSwedishPlace } from '@/lib/geo';
import { calculateRentalPricing } from '@/lib/rental-pricing';
import { DISCOVERY_ROOTS, categoryBelongsToRoot, categoryIntegrity, categorySearchTerms, rootLabel } from '@/lib/discovery-taxonomy';
import ProductVisual from '@/components/ProductVisual';
import ProductSearchForm from '@/components/ProductSearchForm';
import SearchResults from '@/components/SearchResults';
import { ProductBadgeLabel } from '@/components/ProductPricing';
import { CategoryIcon } from '@/components/Icons';

function normalize(v:string|undefined){return(v??'').trim().toLocaleLowerCase('sv-SE')}

export default async function ProductsPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{category?:string;q?:string;from?:string;to?:string;place?:string;radius?:string;nearby?:string;edit?:string}>}){
 const {locale}=await params,sp=await searchParams;const {category,q,from,to,place,radius,nearby,edit}=sp,en=locale==='en',products=await getProducts();
 const reviewSummaries=await getProductReviewSummaries(products.flatMap(p=>p.id?[p.id]:[]));
 const selectedCategory=DISCOVERY_ROOTS.includes(category||'')?category:undefined,query=normalize(q),requestedFrom=from||to,requestedTo=to||from;
 const integrity=categoryIntegrity(products.map(p=>p.category));if(integrity.unknown.length)console.warn('Discovery found unmapped product categories',integrity.unknown);
 const [legacyUnavailableSlugs,bookedProductIds]=requestedFrom?await Promise.all([getUnavailableProductSlugs(requestedFrom,requestedTo),getUnavailableProductIds(requestedFrom,requestedTo)]):[new Set<string>(),new Set<string>()];
 const unavailableSlugs=new Set<string>(legacyUnavailableSlugs);for(const product of products)if(product.id&&bookedProductIds.has(product.id))unavailableSlugs.add(product.slug);
 const searched=Boolean(query||from||to||place||nearby==='1'),locationRequested=Boolean(place||nearby==='1'),searchPlace=place?.trim()||'Danderyd',searchRadius=Math.max(1,Math.min(50,Number(radius||10)||10)),searchCenter=locationRequested?await geocodeSwedishPlace(searchPlace):null;
 const filtered=products.filter(p=>{if(selectedCategory&&!categoryBelongsToRoot(p.category,selectedCategory))return false;if(query){const terms=[p.brand,p.name,p.type,p.typeEn,p.category,...categorySearchTerms(p.category)].map(normalize).join(' ');if(!terms.includes(query))return false}if(requestedFrom&&unavailableSlugs.has(p.slug))return false;if(locationRequested&&searchCenter){const point=p.pickupLocation;if(!point)return false;return distanceKm(searchCenter,{lat:point.lat,lng:point.lng})<=searchRadius}return true}).sort((a,b)=>{if(searchCenter&&a.pickupLocation&&b.pickupLocation){const da=distanceKm(searchCenter,{lat:a.pickupLocation.lat,lng:a.pickupLocation.lng}),db=distanceKm(searchCenter,{lat:b.pickupLocation.lat,lng:b.pickupLocation.lng});if(Math.abs(da-db)>.01)return da-db}return(en?(a.typeEn??a.type):a.type).localeCompare(en?(b.typeEn??b.type):b.type,en?'en':'sv',{sensitivity:'base'})});
 const rootCounts=new Map(DISCOVERY_ROOTS.map(root=>[root,products.filter(p=>categoryBelongsToRoot(p.category,root)).length]));
 const keep=(value?:string)=>{const p=new URLSearchParams();if(value)p.set('category',value);if(q)p.set('q',q);if(from)p.set('from',from);if(to)p.set('to',to);if(place)p.set('place',place);if(radius)p.set('radius',radius);if(nearby==='1')p.set('nearby','1');return`/${locale}/produkter?${p}`};
 const resultItems=filtered.map(p=>{const pricing=from?calculateRentalPricing(p.price,from,to||from,p.rentalPrices,p.discounts):null,qp=new URLSearchParams();if(q)qp.set('q',q);if(selectedCategory)qp.set('category',selectedCategory);if(from)qp.set('from',from);if(to)qp.set('to',to);if(place)qp.set('place',place);if(radius)qp.set('radius',radius);if(nearby==='1')qp.set('nearby','1');const point=p.pickupLocation,distance=searchCenter&&point?distanceKm(searchCenter,{lat:point.lat,lng:point.lng}):undefined,review=p.id?reviewSummaries[p.id]:undefined;return{slug:p.slug,href:`/${locale}/produkter/${p.slug}${searched?`?${qp.toString()}`:''}`,brand:p.brand,name:p.name,type:en?(p.typeEn??p.type):p.type,image:p.image,accent:p.accent,badge:p.badge,priceLabel:pricing?`${pricing.total} kr · ${pricing.days} ${en?(pricing.days===1?'day':'days'):(pricing.days===1?'dag':'dagar')}`:p.price,mapLabel:pricing?`${pricing.total} kr`:p.price,lat:point?.lat,lng:point?.lng,distanceKm:distance,rating:review?.overall,reviewCount:review?.count||0}}),metaLabel=`${filtered.length} ${en?'products':'produkter'}`,locationUnavailable=locationRequested&&!searchCenter;
 const categoryEmpty=Boolean(selectedCategory)&&!products.some(p=>categoryBelongsToRoot(p.category,selectedCategory));
 const productGrid=<><div className="rentMeta2"><span>{metaLabel}</span>{(selectedCategory||searched)&&<Link href={`/${locale}/produkter?edit=1`}>{en?'Clear filters':'Rensa filter'}</Link>}</div><section className="productGrid2">{filtered.map(p=>{const review=p.id?reviewSummaries[p.id]:undefined;const qp=new URLSearchParams();if(q)qp.set('q',q);if(selectedCategory)qp.set('category',selectedCategory);if(from)qp.set('from',from);if(to)qp.set('to',to);if(place)qp.set('place',place);if(radius)qp.set('radius',radius);if(nearby==='1')qp.set('nearby','1');return <Link href={`/${locale}/produkter/${p.slug}${searched?`?${qp.toString()}`:''}`} className="productTile2" key={p.slug}><div className="productTileVisual2"><ProductVisual kind="cleaner" accent={p.accent} imageSrc={p.image} imageAlt={`${p.brand} ${p.name}`}/><ProductBadgeLabel badge={p.badge} locale={locale}/></div><div className="productTileCopy2"><strong className="productTileTitle2"><span className="productTileBrand2">{p.brand}</span><span className="productTileName2">{p.name}</span></strong><span>{en?(p.typeEn??p.type):p.type}</span>{review?.count&&review.overall!=null?<span className="productReviewMini2">★ {review.overall.toFixed(1).replace('.',',')} · {review.count} {en?'reviews':'omdömen'}</span>:null}<b>{p.price}</b></div></Link>})}</section></>;
 return <div className="pageShell rentPage2"><div className="rentSticky2"><header className="brandHeader2"><Link href={`/${locale}`} className="hyrbartWordmark2"><span className="hyrbartWordmarkH2">H<i/></span><span>yrbart</span></Link></header><section className="homeIntro2 rentIntro2"><h1>{en?'What do you want to rent?':'Vad vill du hyra?'}</h1><ProductSearchForm locale={locale} initialQuery={q??''} category={selectedCategory} initialFrom={from??''} initialTo={to??''} initialPlace={place??''} initialRadius={radius??'10'} initialNearby={nearby==='1'} initiallyCollapsed={searched&&edit!=='1'}/></section><div className="categoryStrip2"><Link href={keep()} className={!selectedCategory?'categoryChip2 active':'categoryChip2'}>{en?'All':'Alla'}</Link>{DISCOVERY_ROOTS.map(root=><Link key={root} href={keep(root)} className={selectedCategory===root?'categoryChip2 active':'categoryChip2'}>{rootLabel(root,locale)}{rootCounts.get(root)?<small> {rootCounts.get(root)}</small>:null}</Link>)}</div></div>
 {locationUnavailable?<section className="rentEmpty2"><h2>{en?'Location not found':'Platsen hittades inte'}</h2><p>{en?'Try a city, district or postcode in Sweden.':'Testa en ort, stadsdel eller ett postnummer i Sverige.'}</p><Link href={`/${locale}/produkter?edit=1`}>{en?'Edit search':'Ändra sökning'}</Link></section>:filtered.length?(searchCenter?<SearchResults locale={locale} place={nearby==='1'?(en?'Nearby':'I närheten'):searchPlace} radius={searchRadius} center={searchCenter} items={resultItems} metaLabel={metaLabel}/>:productGrid):<section className="rentEmpty2"><h2>{categoryEmpty?(en?'Nothing listed here yet':'Inget uthyrt här ännu'):(en?'No matches':'Inga träffar')}</h2><p>{categoryEmpty?(en?'This category is ready, but does not have active listings yet. Explore all categories instead.':'Kategorin finns, men har inga aktiva annonser ännu. Utforska alla kategorier i stället.'):requestedFrom?(en?'No available products match your dates and filters. Try other dates or a larger radius.':'Inga lediga produkter matchar dina datum och filter. Prova andra datum eller större radie.'):(searchCenter?(en?`No products found within ${searchRadius} km. Try a larger radius or another location.`:`Inga produkter hittades inom ${searchRadius} km. Prova större radie eller en annan plats.`):(en?'Try another search or category.':'Prova en annan sökning eller kategori.'))}</p><Link href={`/${locale}/produkter?edit=1`}>{en?'Change filters':'Ändra filter'}</Link> · <Link href={`/${locale}/produkter`}>{en?'Show all':'Visa alla'}</Link></section>}
 {!selectedCategory&&!query&&!searched&&<section className="categoryOverview2">{DISCOVERY_ROOTS.map(root=><Link key={root} href={`/${locale}/produkter?category=${encodeURIComponent(root)}`}><CategoryIcon category={root}/><span>{rootLabel(root,locale)}</span><small>{rootCounts.get(root)||0} {en?'items':'objekt'}</small></Link>)}</section>}</div>
}
