import Link from 'next/link';
import { getProducts } from '@/lib/sanity-products';
import ProductVisual from '@/components/ProductVisual';
import ProductSearchForm from '@/components/ProductSearchForm';
import { CategoryIcon } from '@/components/Icons';

const categoryDefinitions = [
  { value: 'Barnartiklar', sv: 'Barnartiklar', en: 'Baby & kids' }, { value: 'Belysning', sv: 'Belysning', en: 'Lighting' }, { value: 'Biltillbehör', sv: 'Biltillbehör', en: 'Car accessories' }, { value: 'Borra & Skruva', sv: 'Borra & Skruva', en: 'Drilling & screwdriving' }, { value: 'Handverktyg', sv: 'Handverktyg', en: 'Hand tools' }, { value: 'Hem & hushåll', sv: 'Hem & hushåll', en: 'Home & household' }, { value: 'Håltagning', sv: 'Håltagning', en: 'Hole making' }, { value: 'Kontor', sv: 'Kontor', en: 'Office' }, { value: 'Luftverktyg', sv: 'Luftverktyg', en: 'Air tools' }, { value: 'Mäta', sv: 'Mäta', en: 'Measuring' }, { value: 'Städa & Tvätta', sv: 'Städa & Tvätta', en: 'Cleaning & washing' }, { value: 'Såga & Slipa', sv: 'Såga & Slipa', en: 'Sawing & sanding' }, { value: 'Trädgård', sv: 'Trädgård', en: 'Garden' }, { value: 'Värme', sv: 'Värme', en: 'Heating' },
];
function normalize(v:string|undefined){return(v??'').trim().toLocaleLowerCase('sv')}
function dailyNumber(price:string){const m=price.match(/([0-9]+(?:[.,][0-9]+)?)/);return m?Number(m[1].replace(',','.')):null}
function daysBetween(a?:string,b?:string){if(!a||!b)return null;const x=new Date(`${a}T12:00:00`),y=new Date(`${b}T12:00:00`);return Math.max(1,Math.round((y.getTime()-x.getTime())/86400000)+1)}
function shortDate(v?:string,en=false){if(!v)return'';return new Intl.DateTimeFormat(en?'en-GB':'sv-SE',{day:'numeric',month:'short'}).format(new Date(`${v}T12:00:00`))}

export default async function ProductsPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{category?:string;q?:string;from?:string;to?:string;place?:string;radius?:string}>}){
 const {locale}=await params; const sp=await searchParams; const {category,q,from,to,place,radius}=sp; const en=locale==='en'; const products=await getProducts(); const selectedCategory=categoryDefinitions.some(i=>i.value===category)?category:undefined; const query=normalize(q); const days=daysBetween(from,to); const searched=Boolean(query||from||to||place);
 const filtered=products.filter(p=>{if(selectedCategory&&p.category!==selectedCategory)return false;if(!query)return true;const c=categoryDefinitions.find(i=>i.value===p.category);return[p.brand,p.name,p.type,p.typeEn,p.category,c?.sv,c?.en].map(normalize).join(' ').includes(query)}).sort((a,b)=>(en?(a.typeEn??a.type):a.type).localeCompare(en?(b.typeEn??b.type):b.type,en?'en':'sv',{sensitivity:'base'}));
 const keep=(value?:string)=>{const p=new URLSearchParams();if(value)p.set('category',value);if(q)p.set('q',q);if(from)p.set('from',from);if(to)p.set('to',to);if(place)p.set('place',place);if(radius)p.set('radius',radius);return`/${locale}/produkter?${p}`};
 return <div className="pageShell rentPage2"><div className="rentSticky2"><header className="brandHeader2"><Link href={`/${locale}`} className="hyrbartWordmark2"><span className="hyrbartWordmarkH2">H<i/></span><span>yrbart</span></Link></header><section className="homeIntro2 rentIntro2"><h1>{en?'What do you want to rent?':'Vad vill du hyra?'}</h1><ProductSearchForm locale={locale} initialQuery={q??''} category={selectedCategory}/></section><div className="categoryStrip2"><Link href={keep()} className={!selectedCategory?'categoryChip2 active':'categoryChip2'}>{en?'All':'Alla'}</Link>{categoryDefinitions.map(i=><Link key={i.value} href={keep(i.value)} className={selectedCategory===i.value?'categoryChip2 active':'categoryChip2'}>{en?i.en:i.sv}</Link>)}</div></div>
 {searched&&<><section className="searchSummary2"><b>{q|| (en?'All products':'Alla produkter')}</b><span>{from&&to?`${shortDate(from,en)} – ${shortDate(to,en)} · `:''}{place||'Danderyd'} · {radius||10} km</span></section><section className="resultsMap2" aria-label={en?'Map of search results':'Karta över sökresultat'}><div className="mapRoad2 r1"/><div className="mapRoad2 r2"/><div className="mapWater2"/>{filtered.slice(0,5).map((p,i)=>{const d=dailyNumber(p.price);const total=d&&days?Math.round(d*days):d;return <span key={p.slug} className={`mapPrice2 m${i+1}`}>{total?`${total} kr`:'Hyrbart'}</span>})}<span className="mapPlace2">{place||'Danderyd'}</span></section></>}
 <div className="rentMeta2"><span>{filtered.length} {en?'products':'produkter'}</span>{(selectedCategory||query)&&<Link href={`/${locale}/produkter`}>{en?'Clear filters':'Rensa filter'}</Link>}</div>
 {filtered.length?<section className="productGrid2">{filtered.map(p=>{const daily=dailyNumber(p.price);const total=daily&&days?Math.round(daily*days):null;return <Link href={`/${locale}/produkter/${p.slug}${searched?`?${new URLSearchParams({...(from?{from}:{}),...(to?{to}:{}),...(place?{place}:{}),...(radius?{radius}:{})}).toString()}`:''}`} className="productTile2" key={p.slug}><div className="productTileVisual2"><ProductVisual kind="cleaner" accent={p.accent} imageSrc={p.image} imageAlt={`${p.brand} ${p.name}`}/></div><div className="productTileCopy2"><strong>{p.brand} {p.name}</strong><span>{en?(p.typeEn??p.type):p.type}</span><b>{total?`${total} kr · ${days} ${en?'days':'dagar'}`:p.price}</b></div></Link>})}</section>:<section className="rentEmpty2"><h2>{en?'No matches':'Inga träffar'}</h2><p>{en?'Try another search or clear the filters.':'Testa en annan sökning eller rensa filtren.'}</p></section>}
 {!selectedCategory&&!query&&!searched&&<section className="categoryOverview2">{categoryDefinitions.map(i=><Link key={i.value} href={`/${locale}/produkter?category=${encodeURIComponent(i.value)}`}><CategoryIcon category={i.value}/><span>{en?i.en:i.sv}</span></Link>)}</section>}</div>
}
