import Link from 'next/link';
import '../../profile-menu.css';

export default async function PersonalDataPage({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params;const en=locale==='en';
 return <section className="ds2Page profileSettingsPage">
  <header className="profileSubHeader"><Link href={`/topsecret/${locale}/profil/sekretess`} aria-label={en?'Back':'Tillbaka'}>‹</Link><h1>{en?'Personal data':'Personuppgifter'}</h1></header>
  <p className="profileSettingsIntro">{en?'This product view explains the main categories Hyrbart currently processes. A legally reviewed privacy notice must define final legal bases, recipients and retention periods before public launch.':'Den här produktvyn beskriver de huvudsakliga kategorier Hyrbart behandlar i nuläget. En juridiskt granskad integritetspolicy behöver fastställa slutliga rättsliga grunder, mottagare och lagringstider före publik lansering.'}</p>
  <section className="profileSettingsCard"><div className="profileSettingsCardHeading"><span>{en?'ACCOUNT':'KONTO'}</span><h2>{en?'Profile and sign-in data':'Profil- och inloggningsuppgifter'}</h2></div><p>{en?'Examples include email address, display name, city, profile image, verification state and security/session information needed to provide and protect your account.':'Exempel är e-postadress, visningsnamn, ort, profilbild, verifieringsstatus och säkerhets-/sessionsuppgifter som krävs för att tillhandahålla och skydda kontot.'}</p></section>
  <section className="profileSettingsCard"><div className="profileSettingsCardHeading"><span>{en?'SERVICE':'TJÄNSTEN'}</span><h2>{en?'Rentals, payments and communication':'Uthyrningar, betalningar och kommunikation'}</h2></div><p>{en?'Bookings, availability, payments, messages, reviews, support and dispute handling use data connected to those actions so the rental agreement can be performed and the marketplace can be kept safe.':'Bokningar, tillgänglighet, betalningar, meddelanden, omdömen, support och tvister använder uppgifter kopplade till dessa händelser för att hyresavtalet ska kunna genomföras och marknadsplatsen hållas säker.'}</p></section>
  <section className="profileSettingsCard"><div className="profileSettingsCardHeading"><span>{en?'OPTIONAL':'VALFRITT'}</span><h2>{en?'Consent-based use':'Samtyckesbaserad användning'}</h2></div><p>{en?'Optional product research, marketing measurement, marketing push and personalization are controlled separately on the Privacy page and are off by default until you choose otherwise.':'Valfri produktanalys, marknadsföringsmätning, marknadsföringspush och personalisering styrs separat på Sekretess-sidan och är avstängda som standard tills du själv väljer annat.'}</p></section>
  <section className="profileSettingsCard"><div className="profileSettingsCardHeading"><span>{en?'YOUR RIGHTS':'DINA RÄTTIGHETER'}</span><h2>{en?'Access, correction, deletion and objection':'Tillgång, rättelse, radering och invändning'}</h2></div><p>{en?'You can correct basic profile data in Account settings and withdraw optional consent on the Privacy page. Secure export and account deletion are tracked in SCRUM-22. Privacy questions and rights requests should use Hyrbart support until a dedicated privacy contact is published.':'Du kan rätta grundläggande profiluppgifter i Kontoinställningar och återkalla valfria samtycken på Sekretess-sidan. Säker export och kontoradering hanteras i SCRUM-22. Frågor och rättighetsbegäranden går tills vidare via Hyrbarts support tills en särskild integritetskontakt publiceras.'}</p><Link className="profilePrimaryAction" href={`/topsecret/${locale}/profil/hjalp`}>{en?'Contact support':'Kontakta support'}</Link></section>
 </section>
}
