export type CategoryNode={name:string;hyggloId?:number;children?:readonly CategoryNode[]};
const leaf=(name:string,hyggloId?:number):CategoryNode=>({name,hyggloId});
const leaves=(names:readonly string[])=>names.map(name=>leaf(name));
const branch=(name:string,hyggloId:number|undefined,children:readonly CategoryNode[]):CategoryNode=>({name,hyggloId,children});

export const CATEGORY_TAXONOMY:readonly CategoryNode[]=[
branch('Bygg & verktyg',17,[
 branch('Anläggningsmaskiner',8739,leaves(['Anläggningsraka','Betong & armering','Jordborr','Markvibrator','Stenklipp','Övrigt inom anläggningsmaskiner'])),leaf('Arbetsbelysning',182),
 branch('Borrmaskiner och skruvdragare',171,leaves(['Bergborr','Bitssats','Borrar','Borrhammare','Borrmaskin','Hålsåg','Mejselhammare / Bilmaskin','Mutterdragare','Pelarborr','Skruvdragare','Slagborrmaskin','Spräckkilar','Vinkelborr','Övrigt inom borrmaskiner och skruvdragare'])),
 branch('Byggmaskiner',8737,leaves(['Dumper','Grävmaskin','Lastare','Minidumper','Skylift','Traktor','Övrigt inom byggmaskiner'])),
 branch('Elmaterial & energi',8738,leaves(['Batterier & batteriladdare','Dragfjäder','Elcentral','Elverk','Elvinda och elkabel','Kabelskalare'])),
 branch('Fräsa & hyvla',175,leaves(['Fräs','Fräsbord','Handhyvel','Planhyvel','Svarv','Övrigt inom fräs & hyvla'])),
 branch('Golvläggning & plattsättning',8956,leaves(['Golvslip','Kakelskärare','Laminatskärare','Mattstripper','Paket för golvläggning','Paket för plattsättning','Trallverktyg','Övrigt inom golvläggning och plattsättning'])),
 branch('Handverktyg',178,leaves(['Avdragare','Fogpistol','Gångjärnsriktare','Hammare','Hylsnycklar','Kofot','Limpistol','Lödkolv','Momentnyckel','Skiftnyckel','Skruvstäd','Slagskruvmejsel','Slägga','Tvingar','Tänger','Verktygslåda','Övrigt inom handverktyg'])),leaf('Hole in one / Dossökare',8676),
 branch('Mätinstrument',173,leaves(['Decibelmätare','Energimätare','Fuktmätare','IR-termometer','Kabelsökare','Krysslaser','Laseravståndsmätare','Ljusmätare','Luftflödesmätare','Luftkvalitetsmätare','Metalldetektor','Multimeter','Måttband','Oscilloskop','Radonmätare','Regelsökare','Rotationslaser','Totalstation','Vattenpass','Vinkelmätare','Värmekamera','Våg','Övrigt inom mätinstrument'])),
 branch('Målning och tapet',176,leaves(['Färgborttagare','Färgkarta NCS','Färgscanner','Färgspruta','Målarbockar','Omrörare','Putsspruta','Rollbox','Tapetbord','Tapetborttagare','Övrigt inom måla'])),leaf('Skyddsutrustning',8546),
 branch('Slipning och polering',174,leaves(['Bandslip','Bänkslip','Excenterslip','Fingerslip','Giraffslip','Golvslip','Gravyrmaskin','Planslip','Polermaskin','Slipmus','Varmluftspistol','Vinkelslip','Övriga slipmaskiner','Övrigt inom slipa'])),branch('Spik- och häftpistoler',9503,leaves(['Häftpistol','Spikpistol'])),
 branch('Ställningar',179,leaves(['Arbetsbänk','Byggstaket','Byggställning','Fodervagn','Fönsterparaply','Gipsvagn','Målarbockar','Skivhiss','Stämp och Monteringsstöd','Tapetbord','Övrigt inom ställningar'])),branch('Svets',177,leaves(['Elsvets','Gassvets','MIG-svets','Plastsvets','Svetshjälm','Övrigt inom svets'])),
 branch('Såga & kapa',172,leaves(['Alligatorsåg','Bandsåg','Bordssåg','Bultsax','Cirkelsåg','Gersåg manuell','Handsåg','Kakelskärare','Kap- & gersåg','Kombisåg','Metallkapsåg','Mobilt sågverk','Motorkap','Multiverktyg','Plasmabrännare','Plåtsax','Pressmaskin','Sticksåg','Sågskena','Tigersåg','Övrigt inom sågar & kapa'])),
 branch('Transport & lyft',8749,leaves(['Glaslyft','Handtruck','Pirra','Plattformsvagn','Truck','Vinsch','Övrigt inom transport & lyft'])),branch('Tryckluft',8743,leaves(['Bläster','Kompressor','Tryckluftslang','Övrigt inom tryckluft'])),
 branch('VVS-verktyg',9046,leaves(['Expansionsverktyg','Pressmaskin','Provtryckningspump','Rörböjare','Rörkap','Rörtång','Sanipexverktyg','Övrigt inom VVS-verktyg'])),branch('Ventilation',181,leaves(['Air conditioning','Avfuktare','Fläkt','Luftflödesmätare','Luftfuktare','Luftrenare','Ozongenerator','Ventilationsrensare','Värmefläkt','Värmelement','Övrigt inom ventilation'])),leaf('Verktygspaket',8601),leaf('Övrigt inom bygg & verktyg',183)
]),
branch('Elektronik',29,[
 branch('Datorer & tillbehör',291,leaves(['4G-router / mobilt bredband','Bärbara datorer','Datortillbehör','Nätverksutrustning','Ritplatta','Skärmar','Stationär dator','Övrigt inom datorer'])),
 branch('Drönare',297,leaves(['DJI Avata','DJI FPV','DJI Inspire','DJI Mavic','DJI Phantom','DJI Spark','Tillbehör till drönare','Undervattensdrönare','Övriga drönare'])),leaf('FM-radio',9349),leaf('Inverter',9397),leaf('Komradio',8499),
 branch('Kontorsmaskiner',294,leaves(['3D-skrivare','Dokumentförstörare','Etikettskrivare','Foto- och diascanner','Lamineringsmaskin','Laserskärare','Scanner','Skrivare','Skärare','Övrigt inom kontorsmaskiner'])),leaf('Kortterminal',8987),
 branch('Ljud',296,leaves(['DJ-utrustning','Högtalare','Hörlurar','Ljudkort','Loop Station','Mikrofon','Musikinstrument','PA','Portabla högtalare','Övrigt inom ljud'])),
 branch('Mobil & surfplatta',298,leaves(['Gimbal för mobiltelefon','Mobiltelefoner','Smartwatch','Solcellsladdare','Surfplattor','Tillbehör till mobiler & surfplattor'])),
 branch('Projektor & TV',293,leaves(['DVD & blu-ray','Diabildsprojektor','Mediaspelare','OH-projektor','Projektor','Projektorduk','Storbildsskärm','TV','VHS-spelare','Övrigt inom projektor och TV'])),leaf('Satellitinstrument',9138),leaf('Smart högtalare',9521),branch('TV-spel',295,leaves(['Arkadspel','Handkontroller','Simulatorutrustning','Spel','Spelkonsoler','VR-glasögon','Övrigt inom TV-spel'])),leaf('Övrigt inom elektronik',299)
]),
branch('Fest',33,[
 branch('Festaktiviteter',8411,leaves(['Badtunna','Bastu','Beer pong','Bubbelbad','Chokladfontän','Glass- och slushmaskin','Hoppborg','Karaoke','Photo booth & tillbehör','Popcornvagn','Sockervaddsmaskin','Toastmasterutrustning','Vattenpipa','Övrigt inom festaktiviteter'])),branch('Festdekoration',8640,leaves(['Ballongpump','Discokula','Eldkorg','Kandelabrar och ljusstakar','Röd matta','Styling & inredning','Övrigt inom festdekoration'])),
 branch('Festkök',8655,leaves(['Bänkspis','Dryck','Grill','Gräddsifon','Korvvagn','Paellapanna & stekhäll','Pizzaugn','På bordet','Soppvärmare','Varmhållning','Övrigt inom festkök'])),branch('Festmöbler',8641,leaves(['Bardisk','Bord för fest','Paket: Bord och stolar','Stolar för fest','Ståbord','Övrigt inom festmöbler'])),leaf('Festpaket',9401),branch('Kläder',335,leaves(['Barnkläder','Festkläder','Klädförvaring','Maskeradkläder','Övrigt inom kläder'])),branch('Ljud, ljus & scen',331,leaves(['Ljud','Partyljus','Rökmaskin','Scen','Såpbubbelmaskin','Övrigt inom ljus & rök'])),branch('Partytält',334,leaves(['Partytält 0 - 23 kvm','Partytält 24 - 32 kvm','Partytält större än 32 kvm','Övrigt inom partytält'])),leaf('Terrassvärmare',8639),leaf('Övrigt inom fest',338)
]),
branch('Film & foto',292,[
 branch('Blixtar och ljus',2925,leaves(['Blixttrigger','Kamerablixt','Reflexskärm','Ringlampa','Softbox & paraply','Speed Booster','Studioblixt','Studiolampa','Övrigt inom Blixtar och ljus'])),leaf('Follow focus & objektivstöd',9460),branch('Fotobakgrund',8502,leaves(['Fotobakgrund, enfärgad','Fotobakgrund, motiv','Fotobakgrund, mönster','Greenscreen','Övrigt inom fotobakgrund'])),leaf('Fotoskrivare',9035),leaf('Färgkalibrator',8733),branch('Kamera',9452,leaves(['Analog kamera','Cine- och filmkamera','Kompaktkamera','Polaroidkamera','Specialkameror','Spegellös systemkamera','Systemkamera','Videokamera','Övriga kameror'])),leaf('Kamerabatteri',9034),leaf('Kamerapaket',9458),leaf('Kameraväska',9007),leaf('Minneskort',9033),leaf('Monitor',9030),branch('Objektiv',2926,leaves(['Adapter','Cinema-objektiv','Filter','Mellanformatsobjektiv','Objektiv till Systemkameror','Spegellösa objektiv','Tillbehör till objektiv','Övriga objektiv'])),branch('Stativ & riggar',8416,leaves(['Bilstativ','C-stand','Cable cam','Gimbals & stabiliserare','Glidskena & dolly','Gorillapod','Kamerariggar & axelstativ','Klämmor & grips','Kran & jib','Monopod','Stativhuvud','Trebensstativ','Övrigt inom stativ'])),leaf('Streaming',9245),leaf('Teleprompter',8696),leaf('Undervattenshus till kamera',9417),leaf('Övrigt inom film & foto',2927)
]),
branch('Fordon',24,[
 leaf('ATV/Fyrhjuling',244),branch('Bilar',241,leaves(['Lätt lastbil','Minibuss','Personbil','Skåpbil'])),branch('Biltillbehör',242,leaves(['Batteriladdare för fordon','Bilbarnstol','Cykelhållare','Kanot - och kajakhållare','Kupévärmare','Laddkabel för elbil','Lasthållare för dragkrok','Snowboard- och skidhållare','Snökedjor','Starthjälpare','Takbox','Takräcken','Övrigt inom biltillbehör'])),branch('Båt',25,leaves(['Båttillbehör','Båttrailer','Kanot','Motorbåt','Roddbåt & Jolle','Segelbåt','Seglarkläder','Vattenskoter'])),branch('Campingfordon',27,leaves(['Campervan','Husbil','Husvagn','Övrigt inom husvagn och husbil'])),branch('Hästtransport',8414,leaves(['Hästlastbil','Hästsläp'])),leaf('Lätt lastbil',8888),branch('MC & tillbehör',243,leaves(['MC-släp','Motorcykelutrustning','Motorcyklar','Övrigt inom motorcykel'])),leaf('Moped',8498),leaf('Skåpbil',2414),branch('Släpvagnar',245,leaves(['Bil- och maskinsläp','Båttrailer','Dollyvagn','Gallersläp','MC-släp','Skåpsläp','Släp med kåpa','Släpvagnstillbehör','Timmervagn','Öppen släpvagn','Övrigt inom släpvagnar'])),leaf('Snöskoter',8572),leaf('Tung lastbil',8600),branch('Verkstad',8630,leaves(['Batteriladdare för fordon','Bilverktyg','Domkraft & pallbockar','Däck- och hjulverktyg','Felkodsläsare','Induktionsvärmare','Kedjeverktyg för MC','Lyftblock','MC-lyft','Montörsvagn','Motorlyft','Oljebyte','Ramp','Starthjälpare','Vakuumtestare','Verkstadspress','Övrigt inom verkstad'])),leaf('Övriga fordon',246),leaf('Övrigt inom fordon',8497)
]),
branch('Hem & hushåll',453,[
 branch('Barnsaker',46,leaves(['Amningskudde','Babygym','Babymonitor','Barncyklar & tillbehör','Barnkläder','Barnmöbler','Barnvagnar & tillbehör','Bilbarnstol','Bröstpump','Bärsele och bärstolar','Leksaker','Resa med barn','Vällingmaskin','Övrigt inom barnsaker'])),branch('Flytt',8439,leaves(['Bärremmar & selar','Flyttkartonger','Flyttvagn','Pirra','Övrigt inom flytt'])),branch('Husdjur',8595,leaves(['Hundtrimmer','Transportbur','Äggkläckningsmaskin','Övrigt inom husdjur'])),branch('Kök',333,leaves(['Bänkugn','Grytor och kastruller','Honungsslunga','Husgeråd och köksmaskiner','Knivslip','Saftmaja','Sous vide','Torkugn','Öl- och vinbryggning','Övrigt inom kök'])),branch('Personvård',8690,leaves(['Blodtrycksmätare','Hårborttagning','Hårstyling','Övrigt inom personvård'])),branch('Styling & inredning',8423,leaves(['Extrasäng','Möbler','Rekvisita','Styling','Tavlor','Övrigt inom styling & inredning'])),leaf('Symaskin',4535),branch('Tvätt och städning',4536,leaves(['Avloppsrensare','Dammsugare','Fönstertvätt','Mattvätt & textiltvätt','Skurmaskin','Steamer','Strykjärn','Ultraljudstvätt','Ångtvätt','Övrigt inom tvätt & städning'])),leaf('Övrigt inom Hem',4537)
]),
branch('Sport & fritid',39,[
 branch('Cykling',391,leaves(['Barncykel','Cykelhållare','Cykelsläp','Cykelvagn','Cykelväskor','Cyklar','Övrigt inom cykel'])),branch('Friluftsliv',392,leaves(['Bär- & svampplockning','Bärstol','Camping','Dry bags','Friluftskläder','Friluftspaket','Friluftsverktyg','Jakt & fiske','Kikare','Kylbox & kylväska','Myggskydd','Navigering & kommunikation','Pannlampa','Ryggsäck','Turvagn','Vandringsstavar','Övrigt inom friluftsliv'])),branch('Hjälpmedel',8979,leaves(['Elektrisk rullstol','Första hjälpen-kit & HLR','Kryckor','Rullator','Rullstol','Övrigt inom hjälpmedel'])),branch('Lek & hobby',8429,leaves(['Airsoft','Airtrack','Bordshockeyspel','Brädspel & pussel','Bumperball','Flyjumpers','Fotbollsbord','Hobbyfordon','Longboard & skateboard','Magnetfiske','Mikroskop','Paintball','Pokerset','Staffli','Studsmatta','Tatueringsmaskin','Transferpress','Utomhusspel','Vattenlek','Övrigt inom lek & hobby'])),branch('Musikinstrument',395,leaves(['Bas','Blåsinstrument','Cello','Fiol','Förstärkare','Gitarr','Gitarrpedal','Instrumentmikrofon','Keyboard','Ljudkort','Piano','Stativ & kabel','Synthesizer','Trummaskin & sampler','Trummor','Ukulele','Övriga musikinstrument','Övrigt inom musikinstrument'])),branch('Resa',399,leaves(['Cykeltransportväska','Resa med barn','Reseadapter','Resväskor','Specialresväskor','Transportbur','Övrigt inom resa'])),branch('Sport',397,leaves(['Beachvolleyboll','Fotboll','Golf','Inlines','Innebandy','Klättring','Racketsport','Ridsport','Slackline','Övrigt inom sport'])),branch('Träning & gym',396,leaves(['Crosstrainer','Hantlar, vikter och kettlebells','Massage','Motionscykel','Pull-up stång','Träningsmaskiner','Viktväst','Vätskebälte','Yogamattor','Övrigt inom träning & gym'])),branch('Vattensport',394,leaves(['Dykutrustning','Elektrisk surfbräda','Kajak','Kitesurfing','SUP','Surfing','Vattenskidor och wakeboard','Vattenskoter','Vattensportkläder','Vindsurfing','Wingsurf','Åkring','Övrigt inom vattensport'])),branch('Vintersport',393,[leaf('Fjällpulka'),branch('Hockey',3972,leaves(['Hockeyhjälm','Hockeyklubba','Ishockeyskridskor','Övrigt inom hockey'])),leaf('Lavinutrustning'),leaf('Pulka'),leaf('Rullskidor'),leaf('Skidor & snowboard'),leaf('Skridskor'),leaf('Snowracer'),leaf('Snö- och isklättring'),leaf('Snöskoter'),leaf('Vinterkläder'),leaf('Övrigt inom vintersport')]),leaf('Övrigt inom sport och fritid',3994)
]),
branch('Trädgård',22,[branch('Gräsmattevård',9508,leaves(['Dressraka','Gallervält','Gräsklippare','Kabelläggningsmaskin','Kabelsökare','Kantskärare','Slätvält','Spridare','Vertikalskärare','Övrigt inom gräsmattevård'])),branch('Stege',2222,leaves(['Kombistege','Stegpall','Teleskopstege','Trapphusstege','Trappstege','Vanlig stege'])),branch('Trädgårdsmaskiner',221,leaves(['Dräneringspump','Flismaskin','Gödselsug','Häcksax','Hängrännerensare','Högtryckstvätt','Jordfräs','Jordsåll','Kompostkvarn','Lövblås','Motorsåg','Poolrobot','Röjsåg & grästrimmer','Snöslunga','Sopmaskin','Stubbfräs','Taktvätt','Terrassborste','Vedklyv','Vedprocessor','Övrigt inom trädgårdsmaskiner'])),leaf('Trädgårdsmöbler',9396),branch('Trädgårdsredskap',222,leaves(['Eldningstunna','Fruktplockare','Grensåg & grensax','Hacka','Hålpipsluftare','Järnspett','Lastvagn','Ogräsbekämpning','Skadedjursbekämpning','Skottkärra','Snöhyvel','Spade','Stamp','Stolpnedslagare','Tryckspruta','Trädgårdsslang','Yxa','Övrigt inom trädgårdsredskap'])),leaf('Övrigt inom trädgård',223)]),
branch('Övrigt',45,[branch('Lokaler',452,leaves(['Förråd','Kontor','Parkering / Garage','Studio','Stuga','Övriga lokaler']))])
] as const;

export function slugifyCategory(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'-och-').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export function categoryPathValue(path:readonly string[]){return path.map(slugifyCategory).join('/')}
export function leafCategories(){const result:{name:string;path:string[];value:string;hyggloId?:number}[]=[];const walk=(nodes:readonly CategoryNode[],parents:string[])=>nodes.forEach(node=>{const path=[...parents,node.name];if(node.children?.length)walk(node.children,path);else result.push({name:node.name,path,value:categoryPathValue(path),hyggloId:node.hyggloId})});walk(CATEGORY_TAXONOMY,[]);return result}
