import 'server-only';
import { createAdminClient } from '@/lib/supabase/admin';

type ReviewRow={booking_id:string;reviewer_role:'renter'|'owner';reviewee_id:string;communication:number;condition_rating:number|null;function_rating:number|null;handover_rating:number|null;return_condition_rating:number|null;overall_rating:number;recommend_person:boolean;recommend_product:boolean|null;comment:string|null;communication_tags:string[];condition_tags:string[];function_tags:string[];handover_tags:string[];return_condition_tags:string[];submitted_at:string};
type BookingRow={id:string;product_id:string;owner_id:string;renter_id:string;status:string;updated_at:string;created_at:string};
export type ReviewSummary={count:number;overall:number|null;communication:number|null;condition:number|null;function:number|null;handover:number|null;returnCondition:number|null;recommendPersonPercent:number|null;recommendProductPercent:number|null;topTags:string[]};
const empty:ReviewSummary={count:0,overall:null,communication:null,condition:null,function:null,handover:null,returnCondition:null,recommendPersonPercent:null,recommendProductPercent:null,topTags:[]};
const avg=(a:number[])=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
function published(review:ReviewRow,booking:BookingRow,all:ReviewRow[]){const pair=all.filter(r=>r.booking_id===review.booking_id);return pair.length>=2||Date.now()>new Date(booking.updated_at||booking.created_at).getTime()+7*86400000}
function summarize(rows:ReviewRow[]):ReviewSummary{if(!rows.length)return empty;const tags=new Map<string,number>();rows.forEach(r=>[...r.communication_tags,...r.condition_tags,...r.function_tags,...r.handover_tags,...r.return_condition_tags].forEach(t=>tags.set(t,(tags.get(t)||0)+1)));const personAnswers=rows.filter(r=>typeof r.recommend_person==='boolean');const productAnswers=rows.filter(r=>typeof r.recommend_product==='boolean');return{count:rows.length,overall:avg(rows.map(r=>r.overall_rating)),communication:avg(rows.map(r=>r.communication)),condition:avg(rows.flatMap(r=>r.condition_rating==null?[]:[r.condition_rating])),function:avg(rows.flatMap(r=>r.function_rating==null?[]:[r.function_rating])),handover:avg(rows.flatMap(r=>r.handover_rating==null?[]:[r.handover_rating])),returnCondition:avg(rows.flatMap(r=>r.return_condition_rating==null?[]:[r.return_condition_rating])),recommendPersonPercent:personAnswers.length>=3?Math.round(personAnswers.filter(r=>r.recommend_person).length/personAnswers.length*100):null,recommendProductPercent:productAnswers.length>=3?Math.round(productAnswers.filter(r=>r.recommend_product).length/productAnswers.length*100):null,topTags:[...tags.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([t])=>t)}}
async function load(){const admin=createAdminClient();const [{data:reviews},{data:bookings}]=await Promise.all([admin.from('booking_reviews').select('*'),admin.from('bookings').select('id,product_id,owner_id,renter_id,status,updated_at,created_at').eq('status','completed')]);const bs=new Map((bookings||[]).map((b:any)=>[b.id,b as BookingRow]));const all=(reviews||[]) as ReviewRow[];const visible=all.filter(r=>{const b=bs.get(r.booking_id);return b&&published(r,b,all)});return{visible,bookings:bs}}
export async function getProductReviewSummaries(productIds:string[]){const {visible,bookings}=await load();const out:Record<string,ReviewSummary>={};for(const id of productIds){const rows=visible.filter(r=>r.reviewer_role==='renter'&&bookings.get(r.booking_id)?.product_id===id);out[id]=summarize(rows)}return out}
export async function getProductReviewSummary(productId:string){return (await getProductReviewSummaries([productId]))[productId]||empty}
export async function getUserReviewSummary(userId:string,as:'owner'|'renter'){const {visible}=await load();return summarize(visible.filter(r=>r.reviewee_id===userId&&r.reviewer_role===(as==='owner'?'renter':'owner')))}
export async function getPublishedProductReviews(productId:string){const {visible,bookings}=await load();return visible.filter(r=>r.reviewer_role==='renter'&&bookings.get(r.booking_id)?.product_id===productId).sort((a,b)=>new Date(b.submitted_at).getTime()-new Date(a.submitted_at).getTime())}
