import { products as fallbackProducts, type Product, type CancellationPolicy } from '@/lib/products';
const projectId='djps09z6',dataset='production',apiVersion='2026-09-08',hyrbartAccent='#c6f000';
type SanityCrop={top?:number;bottom?:number;left?:number;right?:number};type SanityImage={url?:string;crop?:SanityCrop;dimensions?:{width?:number;height?:number}};
const productProjection=`{"id":_id,brand,name,"slug":slug.current,typeSv,typeEn,category,dailyPrice,multiDayDiscountPercent,weeklyDiscountPercent,repeatCustomerDiscountPercent,cancellationPolicy,"imageItems":images[]{"url":asset->url,crop,hotspot,"dimensions":asset->metadata.dimensions},"legacyImageUrl":image.asset->url,legacyImagePath,badge,rating,reviewCount,cardHighlight{sv,en},rentalPrices[]{days,price},detailCategory{sv,en},included[]{sv,en},description{sv,en},specifications[]{label{sv,en},value},hyggloUrl,supplierUrl,"guideAvailable":count(guideSections)>0,"owner":owner->{"id":_id,"name":displayName,city,"profileImage":profileImage.asset->url,responseTimeMinutes},"pickupLocation":pickupLocation->{"id":_id,name,city,area,"lat":location.lat,"lng":location.lng}}`;
type SanityProduct={id?:string;brand:string;name:string;slug:string;typeSv:string;typeEn?:string;category:string;dailyPrice?:number;multiDayDiscountPercent?:number;weeklyDiscountPercent?:number;repeatCustomerDiscountPercent?:number;cancellationPolicy?:CancellationPolicy;imageItems?:SanityImage[];legacyImageUrl?:string;legacyImagePath?:string;badge?:Product['badge'];rating?:number;reviewCount?:number;cardHighlight?:Product['cardHighlight'];rentalPrices?:Product['rentalPrices'];detailCategory?:Product['detailCategory'];included?:Product['included'];description?:Product['description'];specifications?:Product['specifications'];hyggloUrl?:string;supplierUrl?:string;guideAvailable?:boolean;owner?:Product['owner'];pickupLocation?:Product['pickupLocation']};
function croppedImageUrl(image?:SanityImage){if(!image?.url)return undefined;const{crop,dimensions}=image,w=dimensions?.width,h=dimensions?.height;if(!crop||!w||!h)return image.url;const l=Math.max(0,crop.left??0),r=Math.max(0,crop.right??0),t=Math.max(0,crop.top??0),b=Math.max(0,crop.bottom??0),x=Math.round(l*w),y=Math.round(t*h),rw=Math.max(1,Math.round(w*(1-l-r))),rh=Math.max(1,Math.round(h*(1-t-b))),url=new URL(image.url);url.searchParams.set('rect',`${x},${y},${rw},${rh}`);return url.toString()}
function mapProduct(i:SanityProduct):Product{const legacy=i.rentalPrices?.find(p=>p.days===1)?.price,one=i.dailyPrice??legacy,images=i.imageItems?.map(croppedImageUrl).filter((u):u is string=>Boolean(u))??[],main=images[0]||i.legacyImageUrl||i.legacyImagePath;return{id:i.id,slug:i.slug,brand:i.brand,name:i.name,type:i.typeSv,typeEn:i.typeEn,price:one?`fr. ${one} kr/dygn`:'',dailyPrice:one,discounts:{multiDayPercent:i.multiDayDiscountPercent,weeklyPercent:i.weeklyDiscountPercent,repeatCustomerPercent:i.repeatCustomerDiscountPercent},cancellationPolicy:i.cancellationPolicy||'moderate',category:i.category,accent:hyrbartAccent,image:main,images:images.length?images:main?[main]:undefined,badge:i.badge||undefined,rating:i.rating??undefined,reviewCount:i.reviewCount??undefined,cardHighlight:i.cardHighlight,rentalPrices:i.rentalPrices,detailCategory:i.detailCategory,included:i.included,description:i.description,specifications:i.specifications,guideAvailable:i.guideAvailable||undefined,hyggloUrl:i.hyggloUrl,supplierUrl:i.supplierUrl,owner:i.owner,pickupLocation:i.pickupLocation}}
async function sanityQuery<T>(query:string):Promise<T>{const response=await fetch(`https://${projectId}.api.sanity.io/v${apiVersion}/data/query/${dataset}?query=${encodeURIComponent(query)}`,{cache:'no-store'});if(!response.ok)throw new Error(`Sanity request failed: ${response.status}`);return((await response.json())as{result:T}).result}
export async function getUnavailableProductSlugs(from?:string,to?:string){if(!from)return new Set<string>();const end=to||from;try{const result=await sanityQuery<Array<{slug?:string}>>(`*[_type=="availabilityBlock"&&defined(product)&&from<=${JSON.stringify(end)}&&to>=${JSON.stringify(from)}]{"slug":product->slug.current}`);return new Set(result.map(i=>i.slug).filter((s):s is string=>Boolean(s)))}catch(e){console.error('Could not load availability from Sanity. Treating products as available.',e);return new Set<string>()}}
export async function getProducts():Promise<Product[]>{try{const result=await sanityQuery<SanityProduct[]>(`*[_type=="product"&&defined(slug.current)&&(!defined(listingStatus)||listingStatus=="active")] ${productProjection}`);return result.length?result.map(mapProduct):fallbackProducts}catch(e){console.error('Could not load products from Sanity. Using local fallback.',e);return fallbackProducts}}
export async function getProduct(slug:string):Promise<Product|undefined>{try{const result=await sanityQuery<SanityProduct|null>(`*[_type=="product"&&slug.current==${JSON.stringify(slug)}&&(!defined(listingStatus)||listingStatus=="active")][0] ${productProjection}`);return result?mapProduct(result):undefined}catch(e){console.error(`Could not load ${slug} from Sanity. Using local fallback.`,e);return fallbackProducts.find(p=>p.slug===slug)}}
