import { defineArrayMember, defineField, defineType } from 'sanity';
import { BadgeInput, RentalPricesInput, TranslationToolInput } from './TranslationToolInput';

export const localizedString = defineType({ name:'localizedString',title:'Lokaliserad korttext',type:'object',fields:[defineField({name:'sv',title:'Svenska',type:'string'}),defineField({name:'en',title:'Engelska',type:'string'})] });
export const localizedText = defineType({ name:'localizedText',title:'Lokaliserad text',type:'object',fields:[defineField({name:'sv',title:'Svenska',type:'text',rows:4}),defineField({name:'en',title:'Engelska',type:'text',rows:4})] });
export const rentalPrice = defineType({ name:'rentalPrice',title:'Hyrespris',type:'object',fields:[defineField({name:'days',title:'Antal dagar',type:'number'}),defineField({name:'price',title:'Pris',type:'number'})] });
export const specification = defineType({ name:'specification',title:'Specifikation',type:'object',fields:[defineField({name:'label',title:'Rubrik',type:'localizedString'}),defineField({name:'value',title:'Värde',type:'string'})] });
export const guideCard = defineType({ name:'guideCard',title:'Guidekort',type:'object',fields:[defineField({name:'title',title:'Rubrik',type:'localizedString'}),defineField({name:'body',title:'Text',type:'localizedText'})] });
export const guideSection = defineType({name:'guideSection',title:'Guidesektion',type:'object',fields:[defineField({name:'key',title:'Nyckel',type:'string'}),defineField({name:'stepNumber',title:'Stegnummer',type:'number'}),defineField({name:'title',title:'Rubrik',type:'localizedString'}),defineField({name:'intro',title:'Introduktion',type:'localizedText'}),defineField({name:'cards',title:'Guidekort',type:'array',of:[defineArrayMember({type:'guideCard'})]}),defineField({name:'infoBox',title:'Informationsruta',type:'object',fields:[defineField({name:'title',title:'Rubrik',type:'localizedString'}),defineField({name:'body',title:'Text',type:'localizedText'})]})]});

export const userProfile = defineType({name:'userProfile',title:'Användare',type:'document',fields:[defineField({name:'displayName',title:'Namn',type:'string',validation:r=>r.required()}),defineField({name:'city',title:'Ort',type:'string'}),defineField({name:'profileImage',title:'Profilbild',type:'image',options:{hotspot:true}}),defineField({name:'bio',title:'Om användaren',type:'text',rows:3})],preview:{select:{title:'displayName',subtitle:'city',media:'profileImage'}}});
export const pickupLocation = defineType({name:'pickupLocation',title:'Utlämningsplats',type:'document',fields:[defineField({name:'name',title:'Namn på plats',type:'string',validation:r=>r.required()}),defineField({name:'owner',title:'Uthyrare',type:'reference',to:[{type:'userProfile'}],validation:r=>r.required()}),defineField({name:'city',title:'Ort',type:'string',validation:r=>r.required()}),defineField({name:'area',title:'Område',type:'string'}),defineField({name:'address',title:'Exakt adress (privat)',type:'string'}),defineField({name:'location',title:'Position',type:'geopoint',validation:r=>r.required()})],preview:{select:{name:'name',city:'city',owner:'owner.displayName'},prepare({name,city,owner}){return{title:name,subtitle:[owner,city].filter(Boolean).join(' · ')}}}});

export const availabilityBlock = defineType({
  name:'availabilityBlock', title:'Tillgänglighetsblockering', type:'document',
  fields:[
    defineField({name:'product',title:'Annons',type:'reference',to:[{type:'product'}],validation:r=>r.required()}),
    defineField({name:'from',title:'Från',type:'date',validation:r=>r.required()}),
    defineField({name:'to',title:'Till',type:'date',validation:r=>r.required()}),
    defineField({name:'status',title:'Status',type:'string',initialValue:'blocked',options:{layout:'radio',list:[{title:'Blockerad av uthyrare',value:'blocked'},{title:'Bokad',value:'booked'},{title:'Service/underhåll',value:'service'}]}}),
    defineField({name:'note',title:'Intern notering',type:'string'}),
  ],
  preview:{select:{product:'product.name',from:'from',to:'to',status:'status'},prepare({product,from,to,status}){return{title:product||'Blockering',subtitle:`${from||''} – ${to||''} · ${status||'blocked'}`}}}
});

const categories=['Barnartiklar','Belysning','Biltillbehör','Borra & Skruva','Handverktyg','Hem & hushåll','Håltagning','Kontor','Luftverktyg','Mäta','Städa & Tvätta','Såga & Slipa','Trädgård','Värme'];
export const product=defineType({name:'product',title:'Produkt',type:'document',orderings:[{title:'Namn A–Ö',name:'nameAsc',by:[{field:'typeSv',direction:'asc'},{field:'brand',direction:'asc'},{field:'name',direction:'asc'}]},{title:'Namn Ö–A',name:'nameDesc',by:[{field:'typeSv',direction:'desc'},{field:'brand',direction:'desc'},{field:'name',direction:'desc'}]}],fieldsets:[{name:'ratingInfo',options:{columns:2}}],fields:[
 defineField({name:'owner',title:'Uthyrare',type:'reference',to:[{type:'userProfile'}]}),defineField({name:'pickupLocation',title:'Utlämningsplats',type:'reference',to:[{type:'pickupLocation'}]}),defineField({name:'category',title:'Kategori',type:'string',options:{list:categories.map(value=>({title:value,value}))}}),defineField({name:'typeSv',title:'Produkttyp – svenska',type:'string'}),defineField({name:'typeEn',title:'Produkttyp – engelska',type:'string'}),defineField({name:'brand',title:'Varumärke',type:'string'}),defineField({name:'name',title:'Produktnamn',type:'string'}),defineField({name:'cardHighlight',title:'Highlight',type:'localizedString'}),defineField({name:'slug',title:'Web-adress',type:'slug',options:{source:'name'},validation:r=>r.required()}),defineField({name:'images',title:'Produktbilder',type:'array',of:[defineArrayMember({type:'image',options:{hotspot:true}})]}),defineField({name:'badge',title:'Popularitetsstämpel',type:'string',components:{input:BadgeInput},options:{list:[{title:'POPULÄR',value:'popular'},{title:'JÄTTEPOPULÄR',value:'very-popular'}]}}),defineField({name:'rating',title:'Betyg',type:'number',fieldset:'ratingInfo'}),defineField({name:'reviewCount',title:'Antal omdömen',type:'number',fieldset:'ratingInfo'}),defineField({name:'rentalPrices',title:'Hyrespriser',type:'array',of:[defineArrayMember({type:'rentalPrice'})],components:{input:RentalPricesInput}}),defineField({name:'included',title:'Detta ingår',type:'array',of:[defineArrayMember({type:'localizedString'})]}),defineField({name:'description',title:'Produktbeskrivning',type:'localizedText'}),defineField({name:'specifications',title:'Tekniska specifikationer',type:'array',of:[defineArrayMember({type:'specification'})]}),defineField({name:'guideSections',title:'Användarguide',type:'array',of:[defineArrayMember({type:'guideSection'})]}),defineField({name:'hyggloUrl',title:'Hygglo-länk',type:'url'}),defineField({name:'supplierUrl',title:'Länk till leverantörshemsida',type:'url'}),defineField({name:'translationTool',title:'Automatisk översättning',type:'string',components:{input:TranslationToolInput}}),defineField({name:'detailCategory',title:'Kategori på produktsidan (tidigare)',type:'localizedString',hidden:true,readOnly:true}),defineField({name:'accent',title:'Accentfärg (tidigare)',type:'string',hidden:true,readOnly:true}),defineField({name:'image',title:'Äldre huvudbild',type:'image',hidden:true,readOnly:true}),defineField({name:'legacyImagePath',title:'Äldre bildsökväg',type:'string',hidden:true,readOnly:true}),defineField({name:'sortOrder',title:'Sorteringsordning (tidigare)',type:'number',hidden:true,readOnly:true})
],preview:{select:{typeSv:'typeSv',brand:'brand',name:'name',media:'images.0'},prepare({typeSv,brand,name,media}){return{title:[typeSv,brand,name].filter(Boolean).join(' – '),media}}}});

export const schemaTypes=[product,userProfile,pickupLocation,availabilityBlock,localizedString,localizedText,rentalPrice,specification,guideCard,guideSection];
